Repository ember-cli/eslint-plugin-ember, pull requests merged in 2018-12, with the labels that each got.

#347 TravisCI: Remove deprecated `sudo: false` option
  .travis.yml
Labels: Internal

#348 Fix no-restricted-resolver-tests to narrow scope of rule
  lib/rules/no-restricted-resolver-tests.js
  tests/lib/rules/no-restricted-resolver-tests.js
Labels: Bug

#350 Introduce no-ember-super-in-es-classes rule
  README.md
  docs/rules/no-ember-super-in-es-classes.md
  lib/index.js
  lib/recommended-rules.js
  lib/rules/no-ember-super-in-es-classes.js
  tests/lib/rules/no-ember-super-in-es-classes.js
Labels: Enhancement

#355 Update avoid-leaking-state-in-ember-objects.md
  docs/rules/avoid-leaking-state-in-ember-objects.md
Labels: Documentation

#363 no-deeply-nested-dependent-keys-with-each: Add more tests
  tests/lib/rules/no-deeply-nested-dependent-keys-with-each.js
Labels: Internal

#362 assert-arg-order: Fix rule for `Ember.assert()` case
  lib/rules/assert-arg-order.js
  tests/lib/rules/assert-arg-order.js
Labels: Bug

#367 no-invalid-debug-function-arguments: Fix false positives
  lib/rules/no-deeply-nested-dependent-keys-with-each.js
  tests/lib/rules/no-deeply-nested-dependent-keys-with-each.js
Labels: Bug

#368 no-test-and-then: Fix code sample in docs
  docs/rules/no-test-and-then.md
Labels: Documentation
