Repository ember-cli/eslint-plugin-ember, pull requests merged in 2018-11, with the labels that each got.

#309 Make no-observers rule recommended
  README.md
  lib/recommended-rules.js
  lib/rules/no-observers.js
  tests/__snapshots__/recommended.js.snap
Labels: Breaking, Enhancement

#310 Add no-restricted-resolver-tests to recommended.
  README.md
  lib/index.js
  lib/recommended-rules.js
  lib/rules/no-restricted-resolver-tests.js
  tests/__snapshots__/recommended.js.snap
Labels: Breaking, Enhancement

#253 `avoid-using-needs` rule
  README.md
  lib/recommended-rules.js
  lib/rules/avoid-using-needs-in-controllers.js
  lib/utils/ember.js
  tests/lib/rules/avoid-using-needs-in-controllers.js
Labels: Enhancement

#311 Add `avoid-using-needs-in-controllers` to recommended set.
  README.md
  lib/index.js
  lib/recommended-rules.js
  lib/rules/avoid-using-needs-in-controllers.js
  tests/__snapshots__/recommended.js.snap
Labels: Breaking, Enhancement

#336 CI: Use `--runInBand` option of Jest to speed up tests
  .travis.yml
Labels: Internal

#334 package.json: Limit published files to the `lib` folder
  package.json
Labels: Internal

#335 Remove outdated `.nvmrc` file
  .nvmrc
Labels: Internal

#331 Updating no-side-effects to also report on setProperties.
  lib/rules/no-side-effects.js
  tests/lib/rules/no-side-effects.js
Labels: Enhancement

#298 no-jquery: Check for aliased imports from 'jquery' module
  lib/rules/no-jquery.js
  tests/lib/rules/no-jquery.js
Labels: Enhancement

#332 use-brace-expansion: Limit lint rule to only trigger for `computed()` but no other macros
  lib/rules/use-brace-expansion.js
  tests/lib/rules/use-brace-expansion.js
Labels: Bug
