Repository ember-cli/eslint-plugin-ember, pull requests merged in 2018-09, with the labels that each got.

#292 Update `fsevents` to v1.2.4
  yarn.lock
Labels: dependencies

#255 Drop Node 4 support.
  .travis.yml
  package.json
  yarn.lock
Labels: Breaking

#267 Change config to reflect deprecation of experimentalObjectRestSpread
  lib/config/base.js
  lib/rules/no-global-jquery.js
  lib/rules/no-restricted-resolver-tests.js
  package.json
  yarn.lock
Labels: Breaking, Enhancement

#274 Add no-ember-testing-in-module scope to recommended
  README.md
  lib/recommended-rules.js
  lib/rules/no-ember-testing-in-module-scope.js
  tests/__snapshots__/recommended.js.snap
Labels: Breaking, Bug
