Repository ember-cli/eslint-plugin-ember, pull requests merged in 2018-03, with the labels that each got.

#198 Add new scenarios for `require-super-in-init` rule
  lib/rules/require-super-in-init.js
  lib/utils/ember.js
  lib/utils/utils.js
  tests/lib/rules/require-super-in-init.js
  tests/lib/utils/ember-test.js
  tests/lib/utils/utils-test.js
Labels: Bug

#172 Add `--fix` support to `order-in-*` rules
  README.md
  lib/rules/order-in-components.js
  lib/rules/order-in-controllers.js
  lib/rules/order-in-models.js
  lib/rules/order-in-routes.js
  lib/utils/property-order.js
  tests/lib/rules/order-in-components.js
  tests/lib/rules/order-in-controllers.js
  tests/lib/rules/order-in-models.js
  tests/lib/rules/order-in-routes.js
Labels: Enhancement

#242 Update `jest` to v21.2.1
  package.json
  tests/lib/utils/ember-test.js
  yarn.lock
Labels: Internal
