Repository ember-cli/eslint-plugin-ember, pull requests merged in 2019-11, with the labels that each got.

#563 Lint against unnecessary template literals internally
  .eslintrc.js
  lib/rules/no-computed-properties-in-native-classes.js
  lib/rules/require-computed-property-dependencies.js
  tests/lib/rules/new-module-imports.js
  tests/lib/rules/no-arrow-function-computed-properties.js
  tests/lib/rules/use-ember-get-and-set.js
  tests/lib/utils/new-module-test.js
Labels: Internal

#565 Add `ignoreNestedPaths` option (default true) to `no-get` rule
  docs/rules/no-get.md
  lib/rules/no-get.js
  tests/lib/rules/no-get.js
Labels: Enhancement

#562 Add new rule `no-test-module-for`
  README.md
  docs/rules/no-test-module-for.md
  lib/index.js
  lib/recommended-rules.js
  lib/rules/no-test-module-for.js
  lib/utils/types.js
  tests/lib/rules/no-test-module-for.js
Labels: Enhancement

#568 Add tests to ensure plugin exports correct configurations
  tests/plugin-exports.js
Labels: Internal

#561 Add `octane` configuration (experimental)
  .eslintignore
  .prettierignore
  README.md
  lib/config/octane.js
  lib/index.js
  lib/octane-rules.js
  lib/rules/classic-decorator-hooks.js
  lib/rules/classic-decorator-no-classic-methods.js
  lib/rules/no-actions-hash.js
  lib/rules/no-classic-classes.js
  lib/rules/no-classic-components.js
  lib/rules/no-computed-properties-in-native-classes.js
  lib/rules/no-get.js
  lib/rules/no-jquery.js
  lib/rules/require-tagless-components.js
  scripts/update-rules.js
  tests/plugin-exports.js
  tests/rule-setup.js
Labels: Enhancement

#570 Simplify some tests by setting `parserOptions` globally instead of in each individual test case
  tests/lib/rules/alias-model-in-controller.js
  tests/lib/rules/closure-actions.js
  tests/lib/rules/jquery-ember-run.js
  tests/lib/rules/named-functions-in-promises.js
  tests/lib/rules/no-attrs-in-components.js
  tests/lib/rules/no-attrs-snapshot.js
  tests/lib/rules/no-ember-super-in-es-classes.js
  tests/lib/rules/no-empty-attrs.js
  tests/lib/rules/no-function-prototype-extensions.js
  tests/lib/rules/no-jquery.js
  tests/lib/rules/no-observers.js
  tests/lib/rules/no-old-shims.js
  tests/lib/rules/no-on-calls-in-components.js
  tests/lib/rules/no-side-effects.js
  tests/lib/rules/order-in-components.js
  tests/lib/rules/order-in-controllers.js
  tests/lib/rules/order-in-models.js
  tests/lib/rules/order-in-routes.js
  tests/lib/rules/require-return-from-computed.js
  tests/lib/rules/require-super-in-init.js
  tests/lib/rules/routes-segments-snake-case.js
Labels: Internal

#571 Update `avoid-leaking-state-in-ember-objects` rule to handle ternary expressions
  lib/rules/avoid-leaking-state-in-ember-objects.js
  tests/lib/rules/avoid-leaking-state-in-ember-objects.js
Labels: Bug

#573 Update `require-computed-macros` rule to handle `this.get('property')` (in addition to `this.property`)
  lib/rules/require-computed-macros.js
  lib/utils/property-getter.js
  tests/lib/rules/require-computed-macros.js
  tests/lib/utils/property-getter-test.js
Labels: Bug

#575 Update `avoid-leaking-state-in-ember-objects` rule to handle logical expressions
  lib/rules/avoid-leaking-state-in-ember-objects.js
  tests/lib/rules/avoid-leaking-state-in-ember-objects.js
Labels: Bug

#574 Update `reportUnorderedProperties` util function to also work with native classes
  lib/rules/no-unnecessary-service-injection-argument.js
  lib/rules/require-computed-property-dependencies.js
  lib/utils/ember.js
  lib/utils/property-order.js
  lib/utils/types.js
  tests/helpers/faux-context.js
  tests/lib/utils/ember-test.js
  tests/lib/utils/property-order-test.js
Labels: Internal

#579 Fix handling of multi-line property keys by `require-computed-property-dependencies` rule
  lib/utils/property-getter.js
  tests/lib/rules/require-computed-property-dependencies.js
Labels: Bug

#580 Update `no-get` rule to ignore `get()` usages inside proxy objects
  docs/rules/no-get.md
  lib/rules/no-get.js
  lib/utils/ember.js
  tests/lib/rules/no-get.js
  tests/lib/utils/ember-test.js
Labels: Bug

#581 Update `no-get` rule to ignore `get()` usages inside objects implementing `unknownProperty()`
  docs/rules/no-get.md
  lib/rules/no-get.js
  lib/utils/ember.js
  tests/lib/rules/no-get.js
  tests/lib/utils/ember-test.js
Labels: Bug

#587 And missing rule documentation URLs
  .eslintrc.js
  lib/rules/avoid-using-needs-in-controllers.js
  lib/rules/no-actions-hash.js
  lib/rules/no-arrow-function-computed-properties.js
  lib/rules/no-classic-classes.js
  lib/rules/no-deeply-nested-dependent-keys-with-each.js
  lib/rules/no-get.js
  lib/rules/no-incorrect-calls-with-inline-anonymous-functions.js
  lib/rules/no-invalid-debug-function-arguments.js
  lib/rules/no-new-mixins.js
  lib/rules/no-pause-test.js
  lib/rules/no-proxies.js
  lib/rules/no-restricted-resolver-tests.js
  lib/rules/no-test-and-then.js
  lib/rules/no-test-import-export.js
  lib/rules/no-test-module-for.js
  lib/rules/no-unnecessary-index-route.js
  lib/rules/no-unnecessary-route-path-option.js
  lib/rules/no-unnecessary-service-injection-argument.js
  lib/rules/no-volatile-computed-properties.js
  lib/rules/require-computed-macros.js
  lib/rules/require-computed-property-dependencies.js
  lib/rules/route-path-style.js
Labels: Documentation

#582 Add CI check to ensure `yarn update` is run to update docs/autogenerated files
  .travis.yml
Labels: Internal

#586 Update `use-brace-expansion` rule to only report the string arguments of a computed property as the violation (and not the entire computed property function body)
  lib/rules/use-brace-expansion.js
  tests/lib/rules/use-brace-expansion.js
Labels: Bug

#588 Add `type` meta property to each rule
  .eslintrc.js
  lib/rules/alias-model-in-controller.js
  lib/rules/avoid-leaking-state-in-ember-objects.js
  lib/rules/avoid-using-needs-in-controllers.js
  lib/rules/classic-decorator-hooks.js
  lib/rules/classic-decorator-no-classic-methods.js
  lib/rules/closure-actions.js
  lib/rules/computed-property-getters.js
  lib/rules/jquery-ember-run.js
  lib/rules/named-functions-in-promises.js
  lib/rules/new-module-imports.js
  lib/rules/no-actions-hash.js
  lib/rules/no-arrow-function-computed-properties.js
  lib/rules/no-attrs-in-components.js
  lib/rules/no-attrs-snapshot.js
  lib/rules/no-capital-letters-in-routes.js
  lib/rules/no-classic-classes.js
  lib/rules/no-classic-components.js
  lib/rules/no-computed-properties-in-native-classes.js
  lib/rules/no-deeply-nested-dependent-keys-with-each.js
  lib/rules/no-duplicate-dependent-keys.js
  lib/rules/no-ember-super-in-es-classes.js
  lib/rules/no-ember-testing-in-module-scope.js
  lib/rules/no-empty-attrs.js
  lib/rules/no-function-prototype-extensions.js
  lib/rules/no-get.js
  lib/rules/no-global-jquery.js
  lib/rules/no-incorrect-calls-with-inline-anonymous-functions.js
  lib/rules/no-invalid-debug-function-arguments.js
  lib/rules/no-jquery.js
  lib/rules/no-new-mixins.js
  lib/rules/no-observers.js
  lib/rules/no-old-shims.js
  lib/rules/no-on-calls-in-components.js
  lib/rules/no-pause-test.js
  lib/rules/no-proxies.js
  lib/rules/no-restricted-resolver-tests.js
  lib/rules/no-side-effects.js
  lib/rules/no-test-and-then.js
  lib/rules/no-test-import-export.js
  lib/rules/no-test-module-for.js
  lib/rules/no-unnecessary-index-route.js
  lib/rules/no-unnecessary-route-path-option.js
  lib/rules/no-unnecessary-service-injection-argument.js
  lib/rules/no-volatile-computed-properties.js
  lib/rules/order-in-components.js
  lib/rules/order-in-controllers.js
  lib/rules/order-in-models.js
  lib/rules/order-in-routes.js
  lib/rules/require-computed-macros.js
  lib/rules/require-computed-property-dependencies.js
  lib/rules/require-return-from-computed.js
  lib/rules/require-super-in-init.js
  lib/rules/require-tagless-components.js
  lib/rules/route-path-style.js
  lib/rules/routes-segments-snake-case.js
  lib/rules/use-brace-expansion.js
  lib/rules/use-ember-data-rfc-395-imports.js
  lib/rules/use-ember-get-and-set.js
Labels: Documentation

#577 Add autofixer to `no-get` rule
  README.md
  lib/rules/no-get.js
  tests/lib/rules/no-get.js
Labels: Enhancement

#583 Update `no-observers` rule to handle decorators
  docs/rules/no-observers.md
  lib/rules/no-observers.js
  lib/utils/ember.js
  lib/utils/types.js
  tests/lib/rules/no-observers.js
  tests/lib/utils/ember-test.js
Labels: Enhancement

#594 Add new rule `no-get-with-default`
  README.md
  docs/rules/no-get-with-default.md
  lib/index.js
  lib/octane-rules.js
  lib/recommended-rules.js
  lib/rules/no-get-with-default.js
  tests/lib/rules/no-get-with-default.js
Labels: Enhancement

#592 Update `no-classic-classes` rule to catch classic Ember Data model classes
  lib/rules/no-classic-classes.js
  lib/utils/utils.js
  tests/lib/rules/no-classic-classes.js
  tests/lib/utils/utils-test.js
  tests/lib/utils/utils/get-source-module-name-for-identifier-test.js
Labels: Enhancement

#600 Add missing schema validation for options on many rules
  lib/rules/alias-model-in-controller.js
  lib/rules/avoid-using-needs-in-controllers.js
  lib/rules/closure-actions.js
  lib/rules/jquery-ember-run.js
  lib/rules/named-functions-in-promises.js
  lib/rules/new-module-imports.js
  lib/rules/no-actions-hash.js
  lib/rules/no-arrow-function-computed-properties.js
  lib/rules/no-attrs-in-components.js
  lib/rules/no-attrs-snapshot.js
  lib/rules/no-classic-classes.js
  lib/rules/no-classic-components.js
  lib/rules/no-computed-properties-in-native-classes.js
  lib/rules/no-deeply-nested-dependent-keys-with-each.js
  lib/rules/no-duplicate-dependent-keys.js
  lib/rules/no-ember-super-in-es-classes.js
  lib/rules/no-ember-testing-in-module-scope.js
  lib/rules/no-empty-attrs.js
  lib/rules/no-function-prototype-extensions.js
  lib/rules/no-get-with-default.js
  lib/rules/no-global-jquery.js
  lib/rules/no-incorrect-calls-with-inline-anonymous-functions.js
  lib/rules/no-invalid-debug-function-arguments.js
  lib/rules/no-jquery.js
  lib/rules/no-new-mixins.js
  lib/rules/no-observers.js
  lib/rules/no-old-shims.js
  lib/rules/no-on-calls-in-components.js
  lib/rules/no-pause-test.js
  lib/rules/no-proxies.js
  lib/rules/no-restricted-resolver-tests.js
  lib/rules/no-side-effects.js
  lib/rules/no-test-and-then.js
  lib/rules/no-test-import-export.js
  lib/rules/no-test-module-for.js
  lib/rules/no-unnecessary-index-route.js
  lib/rules/no-unnecessary-route-path-option.js
  lib/rules/no-unnecessary-service-injection-argument.js
  lib/rules/no-volatile-computed-properties.js
  lib/rules/order-in-components.js
  lib/rules/order-in-controllers.js
  lib/rules/order-in-models.js
  lib/rules/order-in-routes.js
  lib/rules/require-computed-macros.js
  lib/rules/require-return-from-computed.js
  lib/rules/require-super-in-init.js
  lib/rules/require-tagless-components.js
  lib/rules/route-path-style.js
  lib/rules/routes-segments-snake-case.js
  lib/rules/use-brace-expansion.js
  lib/rules/use-ember-data-rfc-395-imports.js
  lib/rules/use-ember-get-and-set.js
Labels: Bug

#607 Fix spread property bug in `require-super-in-init` rule
  lib/rules/require-super-in-init.js
  tests/lib/rules/require-super-in-init.js
Labels: Bug

#611 Add many missing tests for lines without test coverage
  lib/rules/require-computed-macros.js
  package.json
  tests/lib/rules/avoid-using-needs-in-controllers.js
  tests/lib/rules/classic-decorator-no-classic-methods.js
  tests/lib/rules/computed-property-getters.js
  tests/lib/rules/new-module-imports.js
  tests/lib/rules/no-classic-classes.js
  tests/lib/rules/no-ember-testing-in-module-scope.js
  tests/lib/rules/no-restricted-resolver-tests.js
  tests/lib/rules/no-test-module-for.js
  tests/lib/rules/require-computed-macros.js
  tests/lib/rules/require-super-in-init.js
  tests/lib/rules/use-ember-data-rfc-395-imports.js
  tests/lib/rules/use-ember-get-and-set.js
Labels: Internal

#610 Fix invalid `no-get` rule autofix caused by invalid JS variable name
  lib/rules/no-get.js
  tests/lib/rules/no-get.js
Labels: Bug

#615 Fix issue causing assert to fire in `getSourceModuleName` util function
  lib/utils/import.js
  tests/lib/utils/import-test.js
  tests/lib/utils/utils/get-source-module-name-for-identifier-test.js
Labels: Bug
