Repository ember-cli/eslint-plugin-ember, pull requests merged in 2019-04, with the labels that each got.

#404 Add new `no-get` rule
  README.md
  docs/rules/no-get.md
  lib/index.js
  lib/recommended-rules.js
  lib/rules/no-get.js
  tests/lib/rules/no-get.js
Labels: Enhancement

#403 Add new `no-get-properties` rule
  README.md
  docs/rules/no-get-properties.md
  docs/rules/no-get.md
  lib/index.js
  lib/recommended-rules.js
  lib/rules/no-get-properties.js
  lib/rules/no-get.js
  lib/rules/no-invalid-debug-function-arguments.js
  lib/utils/utils.js
  tests/lib/rules/no-get-properties.js
Labels: Enhancement

#409 Update documentation for `require-return-from-computed` rule
  docs/rules/require-return-from-computed.md
Labels: Documentation

#411 Update contributors
  README.md
Labels: Documentation

#413 Ignore template literals in `no-get` and `no-get-properties` rules
  lib/rules/no-get-properties.js
  lib/rules/no-get.js
  lib/utils/utils.js
  tests/lib/rules/no-get-properties.js
  tests/lib/rules/no-get.js
  tests/lib/utils/utils-test.js
Labels: Bug

#412 Update release instructions
  RELEASE.md
Labels: Documentation
