Repository ember-cli/eslint-plugin-ember, pull requests merged in 2019-10, with the labels that each got.

#462 Refactor null checks for `new-module-imports` and `use-ember-data-rfc-395-imports` rules
  lib/rules/new-module-imports.js
  lib/rules/use-ember-data-rfc-395-imports.js
  lib/utils/new-module.js
  tests/lib/utils/new-module-test.js
Labels: Bug

#537 Add `ignoreGetProperties` option for `no-get` rule
  docs/rules/no-get.md
  lib/rules/no-get.js
  tests/lib/rules/no-get.js
Labels: Enhancement

#534 Add `onlyThisContexts` option to `no-arrow-function-computed-properties` rule
  docs/rules/no-arrow-function-computed-properties.md
  lib/rules/no-arrow-function-computed-properties.js
  tests/lib/rules/no-arrow-function-computed-properties.js
Labels: Enhancement

#545 Add `ignoreNonThisExpressions` option to `use-ember-get-and-set` rule
  docs/rules/use-ember-get-and-set.md
  lib/rules/use-ember-get-and-set.js
  tests/lib/rules/use-ember-get-and-set.js
Labels: Enhancement

#550 Modernize documentation for `alias-model-in-controller` rule
  docs/rules/alias-model-in-controller.md
Labels: Documentation

#546 Add new `no-computed-properties-in-native-classes` rule
  README.md
  docs/rules/no-computed-properties-in-native-classes.md
  lib/index.js
  lib/recommended-rules.js
  lib/rules/no-computed-properties-in-native-classes.js
  tests/lib/rules/no-computed-properties-in-native-classes.js
Labels: Enhancement

#551 Add new `no-classic-components` rule
  README.md
  docs/rules/no-classic-components.md
  lib/index.js
  lib/recommended-rules.js
  lib/rules/no-classic-components.js
  tests/lib/rules/no-classic-components.js
Labels: Enhancement

#554 Add rule documentation template
  docs/rules/_TEMPLATE_.md
  tests/rule-setup.js
Labels: Documentation

#553 Avoid crash from missing function check in `require-super-in-init` rule
  lib/rules/require-super-in-init.js
  tests/lib/rules/require-super-in-init.js
Labels: Bug

#552 Add new `no-classic-classes` rule
  README.md
  docs/rules/no-classic-classes.md
  lib/index.js
  lib/recommended-rules.js
  lib/rules/no-classic-classes.js
  lib/utils/types.js
  lib/utils/utils.js
  tests/lib/rules/no-classic-classes.js
Labels: Enhancement

#548 Add new `require-tagless-components` rule
  README.md
  docs/rules/require-tagless-components.md
  lib/index.js
  lib/recommended-rules.js
  lib/rules/new-module-imports.js
  lib/rules/no-classic-classes.js
  lib/rules/require-tagless-components.js
  lib/rules/use-ember-data-rfc-395-imports.js
  lib/utils/new-module.js
  lib/utils/types.js
  lib/utils/utils.js
  tests/lib/rules/require-tagless-components.js
  tests/lib/utils/utils/get-source-module-name-for-identifier-test.js
Labels: Enhancement

#558 Update `isEmberCoreModule` util function to also handle native classes (in addition to classic classes)
  lib/rules/alias-model-in-controller.js
  lib/rules/avoid-using-needs-in-controllers.js
  lib/rules/no-new-mixins.js
  lib/rules/no-on-calls-in-components.js
  lib/rules/order-in-components.js
  lib/rules/order-in-controllers.js
  lib/rules/order-in-routes.js
  lib/rules/require-super-in-init.js
  lib/rules/require-tagless-components.js
  lib/utils/ember.js
  lib/utils/types.js
  package.json
  tests/helpers/faux-context.js
  tests/lib/utils/ember-test.js
  tests/lib/utils/utils/get-source-module-name-for-identifier-test.js
Labels: Internal

#555 Add new `no-actions-hash` rule
  README.md
  docs/rules/no-actions-hash.md
  lib/index.js
  lib/recommended-rules.js
  lib/rules/no-actions-hash.js
  tests/lib/rules/no-actions-hash.js
Labels: Enhancement
