Repository ember-cli/eslint-plugin-ember, pull requests merged in 2019-09, with the labels that each got.

#503 Refactor utils to move type checking utils to a separate file and alphabetize
  lib/rules/avoid-leaking-state-in-ember-objects.js
  lib/rules/closure-actions.js
  lib/rules/computed-property-getters.js
  lib/rules/jquery-ember-run.js
  lib/rules/named-functions-in-promises.js
  lib/rules/no-arrow-function-computed-properties.js
  lib/rules/no-attrs-in-components.js
  lib/rules/no-capital-letters-in-routes.js
  lib/rules/no-function-prototype-extensions.js
  lib/rules/no-get.js
  lib/rules/no-global-jquery.js
  lib/rules/no-incorrect-calls-with-inline-anonymous-functions.js
  lib/rules/no-invalid-debug-function-arguments.js
  lib/rules/no-jquery.js
  lib/rules/no-on-calls-in-components.js
  lib/rules/no-restricted-resolver-tests.js
  lib/rules/no-side-effects.js
  lib/rules/no-test-and-then.js
  lib/rules/no-unnecessary-route-path-option.js
  lib/rules/no-unnecessary-service-injection-argument.js
  lib/rules/no-volatile-computed-properties.js
  lib/rules/require-computed-macros.js
  lib/rules/require-computed-property-dependencies.js
  lib/rules/require-super-in-init.js
  lib/rules/route-path-style.js
  lib/rules/routes-segments-snake-case.js
  lib/rules/use-brace-expansion.js
  lib/rules/use-ember-get-and-set.js
  lib/utils/ember.js
  lib/utils/property-getter.js
  lib/utils/types.js
  lib/utils/utils.js
  tests/lib/utils/types-test.js
  tests/lib/utils/utils-test.js
Labels: Internal

#506 Add example of a getter with an if statement for `require-return-from-computed` rule
  docs/rules/require-return-from-computed.md
Labels: Documentation

#504 Update `require-computed-property-dependencies` rule to ignore injected service names by default
  docs/rules/require-computed-property-dependencies.md
  lib/rules/require-computed-property-dependencies.js
  lib/utils/types.js
  tests/lib/rules/require-computed-property-dependencies.js
Labels: Bug

#498 Fix decorator handling and improve error messages for `computed-property-getters` rule
  lib/rules/computed-property-getters.js
  tests/lib/rules/computed-property-getters.js
Labels: Bug

#496 Suggest using the eslint `consistent-return` rule alongside `require-return-from-computed` rule to help avoid false positives
  docs/rules/require-return-from-computed.md
Labels: Documentation

#510 Cleanup code samples in some of the new V7 recommended rules
  docs/rules/no-ember-super-in-es-classes.md
  docs/rules/no-new-mixins.md
  docs/rules/require-return-from-computed.md
Labels: Documentation

#516 Test plugin under both eslint 5 and eslint 6
  .travis.yml
Labels: Internal

#507 Add new `no-pause-test` rule
  README.md
  docs/rules/no-pause-test.md
  lib/index.js
  lib/recommended-rules.js
  lib/rules/no-pause-test.js
  tests/lib/rules/no-pause-test.js
Labels: Enhancement

#519 Add CI check to ensure yarn.lock is up-to-date
  .travis.yml
Labels: Internal

#523 Add eslint-plugin-eslint-comments and fix violations
  .eslintignore
  .eslintrc.js
  lib/index.js
  package.json
  scripts/update-rules.js
  yarn.lock
Labels: Internal

#524 Add eslint-plugin-filenames to enforce kebab-case filenames
  .eslintrc.js
  package.json
  tests/lib/utils/property-getter-test.js
  yarn.lock
Labels: Internal

#528 Add eslint-plugin-node and enable recommended rules internally
  .eslintrc.js
  lib/rules/require-computed-property-dependencies.js
  package.json
  tests/plugin-exports.js
  tests/rule-setup.js
  yarn.lock
Labels: Internal
