Repository ember-cli/eslint-plugin-ember, pull requests merged in 2019-12, with the labels that each got.

#620 Use consistent prefixes for rule descriptions
  README.md
  lib/rules/alias-model-in-controller.js
  lib/rules/avoid-leaking-state-in-ember-objects.js
  lib/rules/avoid-using-needs-in-controllers.js
  lib/rules/classic-decorator-hooks.js
  lib/rules/classic-decorator-no-classic-methods.js
  lib/rules/closure-actions.js
  lib/rules/computed-property-getters.js
  lib/rules/jquery-ember-run.js
  lib/rules/named-functions-in-promises.js
  lib/rules/new-module-imports.js
  lib/rules/no-actions-hash.js
  lib/rules/no-arrow-function-computed-properties.js
  lib/rules/no-attrs-in-components.js
  lib/rules/no-attrs-snapshot.js
  lib/rules/no-capital-letters-in-routes.js
  lib/rules/no-classic-classes.js
  lib/rules/no-classic-components.js
  lib/rules/no-computed-properties-in-native-classes.js
  lib/rules/no-deeply-nested-dependent-keys-with-each.js
  lib/rules/no-duplicate-dependent-keys.js
  lib/rules/no-ember-super-in-es-classes.js
  lib/rules/no-ember-testing-in-module-scope.js
  lib/rules/no-empty-attrs.js
  lib/rules/no-function-prototype-extensions.js
  lib/rules/no-get-with-default.js
  lib/rules/no-get.js
  lib/rules/no-global-jquery.js
  lib/rules/no-incorrect-calls-with-inline-anonymous-functions.js
  lib/rules/no-invalid-debug-function-arguments.js
  lib/rules/no-jquery.js
  lib/rules/no-new-mixins.js
  lib/rules/no-observers.js
  lib/rules/no-old-shims.js
  lib/rules/no-on-calls-in-components.js
  lib/rules/no-pause-test.js
  lib/rules/no-proxies.js
  lib/rules/no-restricted-resolver-tests.js
  lib/rules/no-side-effects.js
  lib/rules/no-test-and-then.js
  lib/rules/no-test-import-export.js
  lib/rules/no-test-module-for.js
  lib/rules/no-unnecessary-index-route.js
  lib/rules/no-unnecessary-route-path-option.js
  lib/rules/no-unnecessary-service-injection-argument.js
  lib/rules/no-volatile-computed-properties.js
  lib/rules/order-in-components.js
  lib/rules/order-in-controllers.js
  lib/rules/order-in-models.js
  lib/rules/order-in-routes.js
  lib/rules/require-computed-macros.js
  lib/rules/require-computed-property-dependencies.js
  lib/rules/require-return-from-computed.js
  lib/rules/require-super-in-init.js
  lib/rules/require-tagless-components.js
  lib/rules/route-path-style.js
  lib/rules/routes-segments-snake-case.js
  lib/rules/use-brace-expansion.js
  lib/rules/use-ember-data-rfc-395-imports.js
  lib/rules/use-ember-get-and-set.js
Labels: Documentation

#621 Fix false positive with `ignoreNonThisExpressions` option in `use-ember-get-and-set` rule
  lib/rules/use-ember-get-and-set.js
  tests/lib/rules/use-ember-get-and-set.js
Labels: Bug

#624 Add eslint-plugin-unicorn internally and fix recommended rules
  .eslintrc.js
  lib/rules/alias-model-in-controller.js
  lib/rules/avoid-leaking-state-in-ember-objects.js
  lib/rules/computed-property-getters.js
  lib/rules/jquery-ember-run.js
  lib/rules/named-functions-in-promises.js
  lib/rules/new-module-imports.js
  lib/rules/no-actions-hash.js
  lib/rules/no-attrs-in-components.js
  lib/rules/no-empty-attrs.js
  lib/rules/no-function-prototype-extensions.js
  lib/rules/no-get.js
  lib/rules/no-global-jquery.js
  lib/rules/no-on-calls-in-components.js
  lib/rules/no-side-effects.js
  lib/rules/no-unnecessary-route-path-option.js
  lib/rules/require-computed-property-dependencies.js
  lib/rules/route-path-style.js
  lib/rules/routes-segments-snake-case.js
  lib/rules/use-brace-expansion.js
  lib/rules/use-ember-data-rfc-395-imports.js
  lib/rules/use-ember-get-and-set.js
  lib/utils/ember.js
  lib/utils/new-module.js
  lib/utils/property-order.js
  lib/utils/utils.js
  package.json
  scripts/update-rules.js
  tests/plugin-exports.js
  tests/recommended.js
  tests/rule-setup.js
  yarn.lock
Labels: Internal

#625 Add eslint-plugin-jest internally and enable rules
  .eslintrc.js
  package.json
  tests/__snapshots__/recommended.js.snap
  tests/lib/rules/avoid-leaking-state-in-ember-objects.js
  tests/lib/utils/ember-test.js
  tests/lib/utils/import-test.js
  tests/lib/utils/property-order-test.js
  tests/lib/utils/types-test.js
  tests/lib/utils/utils-test.js
  tests/lib/utils/utils/get-source-module-name-for-identifier-test.js
  tests/plugin-exports.js
  tests/recommended.js
  tests/rule-setup.js
  yarn.lock
Labels: Internal

#626 Simplify and clarify rules and configuration sections in README
  README.md
Labels: Documentation
