Repository ember-cli/eslint-plugin-ember, pull requests merged in 2019-08, with the labels that each got.

#455 Update exporting of rule error messages to rule tests for consistency and for eslint 5 support
  lib/rules/computed-property-getters.js
  lib/rules/no-attrs-snapshot.js
  lib/rules/no-deeply-nested-dependent-keys-with-each.js
  lib/rules/no-duplicate-dependent-keys.js
  lib/rules/no-ember-testing-in-module-scope.js
  lib/rules/no-get-properties.js
  lib/rules/no-global-jquery.js
  lib/rules/no-jquery.js
  lib/rules/no-new-mixins.js
  lib/rules/no-proxies.js
  lib/rules/no-restricted-resolver-tests.js
  lib/rules/no-test-and-then.js
  lib/rules/no-unnecessary-index-route.js
  lib/rules/no-unnecessary-route-path-option.js
  lib/rules/no-unnecessary-service-injection-argument.js
  lib/rules/route-path-style.js
  tests/lib/rules/computed-property-getters.js
  tests/lib/rules/no-attrs-snapshot.js
  tests/lib/rules/no-duplicate-dependent-keys.js
  tests/lib/rules/no-ember-testing-in-module-scope.js
  tests/lib/rules/no-global-jquery.js
  tests/lib/rules/no-jquery.js
  tests/lib/rules/no-new-mixins.js
  tests/lib/rules/no-restricted-resolver-tests.js
Labels: Internal

#456 Upgrade from eslint 4 to 5 (internal-only)
  .eslintrc.js
  package.json
  yarn.lock
Labels: Internal, dependencies

#457 Add new rule `no-arrow-function-computed-properties`
  README.md
  docs/rules/no-arrow-function-computed-properties.md
  lib/index.js
  lib/recommended-rules.js
  lib/rules/no-arrow-function-computed-properties.js
  tests/lib/rules/no-arrow-function-computed-properties.js
Labels: Enhancement

#450 Add new `use-ember-data-rfc-395-imports` rule
  .travis.yml
  README.md
  docs/rules/use-ember-data-rfc-395-imports.md
  lib/index.js
  lib/recommended-rules.js
  lib/rules/new-module-imports.js
  lib/rules/no-empty-attrs.js
  lib/rules/no-old-shims.js
  lib/rules/use-ember-data-rfc-395-imports.js
  lib/utils/new-module.js
  package.json
  tests/lib/rules/new-module-imports.js
  tests/lib/rules/use-ember-data-rfc-395-imports.js
  yarn.lock
Labels: Enhancement

#460 Add null check in `new-module-imports` rule
  lib/utils/new-module.js
  tests/lib/rules/new-module-imports.js
Labels: Bug

#461 Add null check in `new-module-imports` rule (again)
  lib/utils/new-module.js
  tests/lib/rules/new-module-imports.js
Labels: Bug

#463 Fix false positives for import statements with `use-ember-data-rfc-395-imports` rule
  lib/rules/use-ember-data-rfc-395-imports.js
  tests/lib/rules/use-ember-data-rfc-395-imports.js
Labels: Bug

#466 Fix eslint 6 rule test parser error
  tests/lib/rules/classic-decorator-hooks.js
  tests/lib/rules/classic-decorator-no-classic-methods.js
Labels: Internal

#465 Add tests that rules are setup correctly (not missing tests, docs, exports, etc)
  lib/index.js
  tests/rule-setup.js
Labels: Internal

#458 Add new rule `require-computed-property-dependencies`
  .eslintrc.js
  README.md
  docs/rules/require-computed-property-dependencies.md
  lib/index.js
  lib/recommended-rules.js
  lib/rules/require-computed-macros.js
  lib/rules/require-computed-property-dependencies.js
  lib/utils/property-getter.js
  lib/utils/utils.js
  tests/lib/rules/require-computed-macros.js
  tests/lib/rules/require-computed-property-dependencies.js
  tests/lib/utils/property-getter-test.js.js
Labels: Enhancement

#471 Improve detection of missing dependencies in `require-computed-property-dependencies` rule
  lib/rules/require-computed-property-dependencies.js
  tests/lib/rules/require-computed-property-dependencies.js
Labels: Bug

#472 Improve handling of nested keys inside braces for `require-computed-property-dependencies` rule
  lib/rules/require-computed-property-dependencies.js
  tests/lib/rules/require-computed-property-dependencies.js
Labels: Bug

#476 Add `allowDynamicKeys` option (default true) to `require-computed-property-dependencies` rule
  docs/rules/require-computed-property-dependencies.md
  lib/rules/require-computed-property-dependencies.js
  tests/lib/rules/require-computed-property-dependencies.js
Labels: Bug

#473 Add new `no-incorrect-calls-with-inline-anonymous-functions` rule
  README.md
  docs/rules/no-incorrect-calls-with-inline-anonymous-functions.md
  lib/index.js
  lib/recommended-rules.js
  lib/rules/no-incorrect-calls-with-inline-anonymous-functions.js
  lib/utils/utils.js
  tests/lib/rules/no-incorrect-calls-with-inline-anonymous-functions.js
Labels: Enhancement

#480 Update supported Node versions mentioned in README
  README.md
Labels: Documentation

#482 Start testing plugin under Node 12
  .travis.yml
Labels: Internal

#488 Update `require-computed-property-dependencies` rule to support eslint 3 and 4
  lib/rules/require-computed-property-dependencies.js
Labels: Bug

#489 Document eslint 4 as the minimum supported version
  .eslintrc.js
  README.md
  package.json
  yarn.lock
Labels: Documentation

#485 Drop Node 6 support
  .travis.yml
  README.md
  package.json
Labels: Breaking

#487 Remove deprecated rules `avoid-leaking-state-in-components`, `local-modules`, `no-get-properties`
  README.md
  docs/rules/avoid-leaking-state-in-components.md
  docs/rules/local-modules.md
  docs/rules/no-get-properties.md
  docs/rules/use-ember-get-and-set.md
  lib/index.js
  lib/recommended-rules.js
  lib/rules/avoid-leaking-state-in-components.js
  lib/rules/local-modules.js
  lib/rules/no-get-properties.js
  tests/lib/rules/avoid-leaking-state-in-components.js
  tests/lib/rules/local-modules.js
  tests/lib/rules/no-get-properties.js
Labels: Breaking

#486 Enable additional recommended rules (`no-arrow-function-computed-properties`, `no-deeply-nested-dependent-keys-with-each`, `no-deeply-nested-dependent-keys-with-each`, `no-incorrect-calls-with-inline-anonymous-functions`, `no-invalid-debug-function-arguments`, `no-new-mixins`, `no-unnecessary-route-path-option`, `no-volatile-computed-properties`, `require-return-from-computed`)
  README.md
  lib/recommended-rules.js
  lib/rules/no-arrow-function-computed-properties.js
  lib/rules/no-deeply-nested-dependent-keys-with-each.js
  lib/rules/no-ember-super-in-es-classes.js
  lib/rules/no-incorrect-calls-with-inline-anonymous-functions.js
  lib/rules/no-invalid-debug-function-arguments.js
  lib/rules/no-new-mixins.js
  lib/rules/no-unnecessary-route-path-option.js
  lib/rules/no-volatile-computed-properties.js
  lib/rules/require-return-from-computed.js
  tests/__snapshots__/recommended.js.snap
Labels: Breaking

#491 Drop eslint 4 support
  .eslintrc.js
  README.md
  package.json
  yarn.lock
Labels: Breaking
