Repository ember-cli/eslint-plugin-ember, pull requests merged in 2019-03, with the labels that each got.

#395 docs: improve `closure-action` rule examples
  docs/rules/closure-actions.md
Labels: Documentation

#378 Add new `no-unnecessary-service-injection-argument` rule
  README.md
  docs/rules/no-unnecessary-service-injection-argument.md
  lib/index.js
  lib/recommended-rules.js
  lib/rules/no-unnecessary-service-injection-argument.js
  tests/lib/rules/no-unnecessary-service-injection-argument.js
  tests/lib/utils/ember-test.js
Labels: Enhancement

#262 Add new 'require-return-from-computed' rule
  README.md
  docs/rules/require-return-from-computed.md
  lib/index.js
  lib/recommended-rules.js
  lib/rules/require-return-from-computed.js
  tests/lib/rules/require-return-from-computed.js
Labels: Enhancement

#372 Add new 'no-unnecessary-index-route' rule
  README.md
  docs/rules/no-unnecessary-index-route.md
  docs/rules/no-unnecessary-route-path-option.md
  lib/index.js
  lib/recommended-rules.js
  lib/rules/no-unnecessary-index-route.js
  tests/lib/rules/no-unnecessary-index-route.js
  tests/lib/rules/no-unnecessary-route-path-option.js
Labels: Enhancement

#369 Add new 'route-path-style' rule
  README.md
  docs/rules/no-capital-letters-in-routes.md
  docs/rules/no-unnecessary-route-path-option.md
  docs/rules/route-path-style.md
  docs/rules/routes-segments-snake-case.md
  lib/index.js
  lib/recommended-rules.js
  lib/rules/route-path-style.js
  tests/lib/rules/route-path-style.js
Labels: Enhancement

#398 no-unnecessary-route-path-option: fix error when `path` is `undefined`
  lib/rules/no-unnecessary-route-path-option.js
  tests/lib/rules/no-unnecessary-route-path-option.js
Labels: Bug
