Repository ember-cli/eslint-plugin-ember, pull requests merged in 2020-02, with the labels that each got.

#655 Update `no-new-mixins` rule documentation
  docs/rules/no-new-mixins.md
Labels: Documentation

#663 Update rule docs to use consistent headers and fix markdownlint violations
  .markdownlint.json
  docs/rules/_TEMPLATE_.md
  docs/rules/alias-model-in-controller.md
  docs/rules/avoid-leaking-state-in-ember-objects.md
  docs/rules/avoid-using-needs-in-controllers.md
  docs/rules/classic-decorator-hooks.md
  docs/rules/classic-decorator-no-classic-methods.md
  docs/rules/closure-actions.md
  docs/rules/computed-property-getters.md
  docs/rules/jquery-ember-run.md
  docs/rules/named-functions-in-promises.md
  docs/rules/new-module-imports.md
  docs/rules/no-actions-hash.md
  docs/rules/no-attrs-in-components.md
  docs/rules/no-attrs-snapshot.md
  docs/rules/no-capital-letters-in-routes.md
  docs/rules/no-classic-classes.md
  docs/rules/no-classic-components.md
  docs/rules/no-computed-properties-in-native-classes.md
  docs/rules/no-deeply-nested-dependent-keys-with-each.md
  docs/rules/no-duplicate-dependent-keys.md
  docs/rules/no-ember-super-in-es-classes.md
  docs/rules/no-ember-testing-in-module-scope.md
  docs/rules/no-empty-attrs.md
  docs/rules/no-function-prototype-extensions.md
  docs/rules/no-get-with-default.md
  docs/rules/no-get.md
  docs/rules/no-global-jquery.md
  docs/rules/no-incorrect-calls-with-inline-anonymous-functions.md
  docs/rules/no-invalid-debug-function-arguments.md
  docs/rules/no-jquery.md
  docs/rules/no-new-mixins.md
  docs/rules/no-observers.md
  docs/rules/no-old-shims.md
  docs/rules/no-on-calls-in-components.md
  docs/rules/no-pause-test.md
  docs/rules/no-restricted-resolver-tests.md
  docs/rules/no-side-effects.md
  docs/rules/no-test-and-then.md
  docs/rules/no-test-import-export.md
  docs/rules/no-test-module-for.md
  docs/rules/no-unnecessary-index-route.md
  docs/rules/no-unnecessary-route-path-option.md
  docs/rules/no-unnecessary-service-injection-argument.md
  docs/rules/order-in-components.md
  docs/rules/order-in-controllers.md
  docs/rules/order-in-models.md
  docs/rules/order-in-routes.md
  docs/rules/require-computed-macros.md
  docs/rules/require-computed-property-dependencies.md
  docs/rules/require-return-from-computed.md
  docs/rules/require-super-in-init.md
  docs/rules/require-tagless-components.md
  docs/rules/route-path-style.md
  docs/rules/routes-segments-snake-case.md
  docs/rules/use-brace-expansion.md
  docs/rules/use-ember-data-rfc-395-imports.md
  docs/rules/use-ember-get-and-set.md
Labels: Documentation

#664 Update `no-classic-components` rule to only disallow the specific component import
  lib/rules/no-classic-components.js
  lib/utils/types.js
  tests/lib/rules/no-classic-components.js
Labels: Bug

#661 Add new rule `no-controllers`
  README.md
  docs/rules/no-controllers.md
  lib/index.js
  lib/recommended-rules.js
  lib/rules/no-controllers.js
  tests/lib/rules/no-controllers.js
Labels: Enhancement

#670 Update `order-in-*` rules to consider template literals as properties
  lib/utils/ember.js
  tests/lib/rules/order-in-components.js
  tests/lib/utils/ember-test.js
  tests/lib/utils/property-order-test.js
Labels: Bug

#665 Update `order-in-*` rules to support custom ordering of properties
  docs/rules/order-in-components.md
  docs/rules/order-in-controllers.md
  docs/rules/order-in-models.md
  docs/rules/order-in-routes.md
  lib/rules/order-in-routes.js
  lib/utils/property-order.js
  tests/lib/rules/order-in-components.js
  tests/lib/rules/order-in-controllers.js
  tests/lib/rules/order-in-models.js
  tests/lib/rules/order-in-routes.js
  tests/lib/utils/property-order-test.js
Labels: Enhancement

#669 Add "Help Wanted" section to documentation for rules that are missing native JavaScript class support
  docs/rules/alias-model-in-controller.md
  docs/rules/avoid-using-needs-in-controllers.md
  docs/rules/computed-property-getters.md
  docs/rules/no-arrow-function-computed-properties.md
  docs/rules/no-capital-letters-in-routes.md
  docs/rules/no-deeply-nested-dependent-keys-with-each.md
  docs/rules/no-duplicate-dependent-keys.md
  docs/rules/no-empty-attrs.md
  docs/rules/no-side-effects.md
  docs/rules/no-unnecessary-service-injection-argument.md
  docs/rules/no-volatile-computed-properties.md
  docs/rules/order-in-components.md
  docs/rules/order-in-controllers.md
  docs/rules/order-in-models.md
  docs/rules/order-in-routes.md
  docs/rules/require-computed-macros.md
  docs/rules/require-computed-property-dependencies.md
  docs/rules/require-return-from-computed.md
  docs/rules/use-brace-expansion.md
Labels: Documentation

#674 Update `require-computed-property-dependencies` rule to handle basic string concatenation in dependent keys
  lib/rules/require-computed-property-dependencies.js
  tests/lib/rules/require-computed-property-dependencies.js
Labels: Bug

#681 Add new rule `no-legacy-test-waiters`
  README.md
  docs/rules/no-legacy-test-waiters.md
  lib/index.js
  lib/recommended-rules.js
  lib/rules/no-legacy-test-waiters.js
  lib/utils/import.js
  tests/lib/rules/no-legacy-test-waiters.js
  tests/lib/utils/import-test.js
Labels: Enhancement
