Repository ember-cli/eslint-plugin-ember, pull requests merged in 2020-03, with the labels that each got.

#688 Lint code samples with eslint-plugin-markdown
  .eslintrc.js
  README.md
  docs/rules/alias-model-in-controller.md
  docs/rules/avoid-leaking-state-in-ember-objects.md
  docs/rules/avoid-using-needs-in-controllers.md
  docs/rules/classic-decorator-hooks.md
  docs/rules/classic-decorator-no-classic-methods.md
  docs/rules/closure-actions.md
  docs/rules/computed-property-getters.md
  docs/rules/named-functions-in-promises.md
  docs/rules/new-module-imports.md
  docs/rules/no-actions-hash.md
  docs/rules/no-attrs-in-components.md
  docs/rules/no-attrs-snapshot.md
  docs/rules/no-classic-classes.md
  docs/rules/no-computed-properties-in-native-classes.md
  docs/rules/no-controllers.md
  docs/rules/no-deeply-nested-dependent-keys-with-each.md
  docs/rules/no-duplicate-dependent-keys.md
  docs/rules/no-ember-super-in-es-classes.md
  docs/rules/no-ember-testing-in-module-scope.md
  docs/rules/no-empty-attrs.md
  docs/rules/no-function-prototype-extensions.md
  docs/rules/no-get-with-default.md
  docs/rules/no-get.md
  docs/rules/no-global-jquery.md
  docs/rules/no-incorrect-calls-with-inline-anonymous-functions.md
  docs/rules/no-invalid-debug-function-arguments.md
  docs/rules/no-legacy-test-waiters.md
  docs/rules/no-new-mixins.md
  docs/rules/no-observers.md
  docs/rules/no-old-shims.md
  docs/rules/no-on-calls-in-components.md
  docs/rules/no-pause-test.md
  docs/rules/no-restricted-resolver-tests.md
  docs/rules/no-side-effects.md
  docs/rules/no-test-import-export.md
  docs/rules/no-test-module-for.md
  docs/rules/order-in-components.md
  docs/rules/order-in-controllers.md
  docs/rules/order-in-models.md
  docs/rules/order-in-routes.md
  docs/rules/require-computed-macros.md
  docs/rules/require-return-from-computed.md
  docs/rules/require-super-in-init.md
  docs/rules/require-tagless-components.md
  docs/rules/routes-segments-snake-case.md
  docs/rules/use-brace-expansion.md
  docs/rules/use-ember-data-rfc-395-imports.md
  docs/rules/use-ember-get-and-set.md
  package.json
  yarn.lock
Labels: Documentation

#595 Add new rule `no-component-lifecycle-hooks` (included in `octane` config)
  README.md
  docs/rules/no-component-lifecycle-hooks.md
  lib/index.js
  lib/octane-rules.js
  lib/recommended-rules.js
  lib/rules/no-component-lifecycle-hooks.js
  lib/utils/ember.js
  tests/lib/rules/no-component-lifecycle-hooks.js
  tests/lib/utils/ember-test.js
Labels: Enhancement

#694 Add new rule `no-private-routing-service`
  README.md
  docs/rules/no-private-routing-service.md
  lib/index.js
  lib/recommended-rules.js
  lib/rules/no-private-routing-service.js
  tests/lib/rules/no-private-routing-service.js
Labels: Enhancement

#697 Handle service injections with no arguments in `no-private-routing-service` rule
  lib/rules/no-private-routing-service.js
  tests/lib/rules/no-private-routing-service.js
Labels: Bug

#705 Support TypeScript files when checking if rules are running on Ember module or test files
  lib/utils/ember.js
  tests/lib/utils/ember-test.js
Labels: Enhancement

#711 Improve contribute guide for adding new rules
  README.md
Labels: Documentation

#712 Improve path generation in rule setup tests
  tests/rule-setup.js
Labels: Internal

#713 Add tests to ensure each rule documentation file has the right title and an examples section
  docs/rules/alias-model-in-controller.md
  docs/rules/order-in-components.md
  docs/rules/order-in-controllers.md
  docs/rules/order-in-models.md
  docs/rules/order-in-routes.md
  tests/rule-setup.js
Labels: Documentation

#715 Mention if a rule is fixable in its documentation
  README.md
  docs/rules/_TEMPLATE_.md
  docs/rules/no-ember-super-in-es-classes.md
  docs/rules/no-get.md
  docs/rules/no-old-shims.md
  docs/rules/no-unnecessary-route-path-option.md
  docs/rules/no-unnecessary-service-injection-argument.md
  docs/rules/order-in-components.md
  docs/rules/order-in-controllers.md
  docs/rules/order-in-models.md
  docs/rules/order-in-routes.md
  docs/rules/require-computed-macros.md
  docs/rules/require-computed-property-dependencies.md
  docs/rules/use-ember-data-rfc-395-imports.md
  docs/rules/use-ember-get-and-set.md
  tests/rule-setup.js
Labels: Documentation

#716 Revamp the guide for contributing a new rule
  README.md
Labels: Documentation

#718 Add new rule `no-replace-test-comments`
  README.md
  docs/rules/no-replace-test-comments.md
  lib/index.js
  lib/recommended-rules.js
  lib/rules/no-replace-test-comments.js
  tests/lib/rules/no-replace-test-comments.js
Labels: Enhancement

#709 Add new rule `no-invalid-dependent-keys`
  README.md
  docs/rules/no-invalid-dependent-keys.md
  lib/index.js
  lib/recommended-rules.js
  lib/rules/no-invalid-dependent-keys.js
  tests/lib/rules/no-invalid-dependent-keys.js
Labels: Enhancement

#695 Add new rule `no-incorrect-computed-macros`
  README.md
  docs/rules/no-incorrect-computed-macros.md
  docs/rules/require-computed-macros.md
  lib/index.js
  lib/recommended-rules.js
  lib/rules/no-incorrect-computed-macros.js
  lib/utils/types.js
  tests/lib/rules/no-incorrect-computed-macros.js
Labels: Enhancement

#719 Validate imports before reporting violations in `no-invalid-debug-function-arguments` rule
  lib/rules/no-invalid-debug-function-arguments.js
  tests/lib/rules/no-invalid-debug-function-arguments.js
Labels: Bug

#720 Add tests to ensure some computed property rules handle the @computed decorator
  tests/lib/rules/no-deeply-nested-dependent-keys-with-each.js
  tests/lib/rules/no-duplicate-dependent-keys.js
  tests/lib/rules/no-invalid-dependent-keys.js
  tests/lib/rules/use-brace-expansion.js
Labels: Internal

#723 Sort rule categories alphabetically in README
  README.md
  scripts/update-rules.js
Labels: Documentation

#724 Recategorize rules into new groups in README
  README.md
  lib/rules/alias-model-in-controller.js
  lib/rules/avoid-using-needs-in-controllers.js
  lib/rules/classic-decorator-hooks.js
  lib/rules/classic-decorator-no-classic-methods.js
  lib/rules/closure-actions.js
  lib/rules/computed-property-getters.js
  lib/rules/jquery-ember-run.js
  lib/rules/named-functions-in-promises.js
  lib/rules/new-module-imports.js
  lib/rules/no-arrow-function-computed-properties.js
  lib/rules/no-attrs-in-components.js
  lib/rules/no-attrs-snapshot.js
  lib/rules/no-capital-letters-in-routes.js
  lib/rules/no-classic-components.js
  lib/rules/no-component-lifecycle-hooks.js
  lib/rules/no-computed-properties-in-native-classes.js
  lib/rules/no-controllers.js
  lib/rules/no-deeply-nested-dependent-keys-with-each.js
  lib/rules/no-duplicate-dependent-keys.js
  lib/rules/no-ember-super-in-es-classes.js
  lib/rules/no-ember-testing-in-module-scope.js
  lib/rules/no-function-prototype-extensions.js
  lib/rules/no-get-with-default.js
  lib/rules/no-get.js
  lib/rules/no-global-jquery.js
  lib/rules/no-incorrect-calls-with-inline-anonymous-functions.js
  lib/rules/no-incorrect-computed-macros.js
  lib/rules/no-invalid-debug-function-arguments.js
  lib/rules/no-invalid-dependent-keys.js
  lib/rules/no-jquery.js
  lib/rules/no-mixins.js
  lib/rules/no-new-mixins.js
  lib/rules/no-observers.js
  lib/rules/no-old-shims.js
  lib/rules/no-on-calls-in-components.js
  lib/rules/no-private-routing-service.js
  lib/rules/no-restricted-resolver-tests.js
  lib/rules/no-side-effects.js
  lib/rules/no-unnecessary-index-route.js
  lib/rules/no-unnecessary-route-path-option.js
  lib/rules/no-unnecessary-service-injection-argument.js
  lib/rules/no-volatile-computed-properties.js
  lib/rules/require-computed-macros.js
  lib/rules/require-computed-property-dependencies.js
  lib/rules/require-return-from-computed.js
  lib/rules/require-super-in-init.js
  lib/rules/require-tagless-components.js
  lib/rules/route-path-style.js
  lib/rules/routes-segments-snake-case.js
  lib/rules/use-brace-expansion.js
  lib/rules/use-ember-get-and-set.js
  scripts/update-rules.js
Labels: Documentation

#728 Allow brace expansion with `and`, `or` macros in `no-incorrect-computed-macros` rule
  lib/rules/no-incorrect-computed-macros.js
  tests/lib/rules/no-incorrect-computed-macros.js
Labels: Bug

#732 Begin testing under Node 13
  .travis.yml
Labels: Internal

#702 Add new rule `no-invalid-test-waiters`
  README.md
  docs/rules/no-invalid-test-waiters.md
  lib/index.js
  lib/recommended-rules.js
  lib/rules/no-invalid-test-waiters.js
  tests/lib/rules/no-invalid-test-waiters.js
Labels: Enhancement

#738 Use sets instead of arrays for better performance
  lib/rules/classic-decorator-no-classic-methods.js
  lib/rules/named-functions-in-promises.js
  lib/rules/no-function-prototype-extensions.js
  lib/rules/no-global-jquery.js
  lib/rules/no-on-calls-in-components.js
  lib/rules/use-ember-get-and-set.js
  lib/utils/ember.js
  lib/utils/new-module.js
Labels: Enhancement

#737 Mention tracked properties as a fix for `classic-decorator-no-classic-methods`
  docs/rules/classic-decorator-no-classic-methods.md
Labels: Documentation

#741 Switch from Travis to GitHub Actions for CI
  .github/workflows/ci.yml
  .travis.yml
  README.md
Labels: Internal

#742 Detect invalid position of `@each` or `[]` in `no-invalid-dependent-keys` rule
  README.md
  docs/rules/no-invalid-dependent-keys.md
  lib/rules/no-invalid-dependent-keys.js
  tests/lib/rules/no-invalid-dependent-keys.js
Labels: Enhancement

#729 Update `ignoreNestedPaths` option default to `false` for `no-get` rule
  docs/rules/no-get.md
  lib/rules/no-get.js
  tests/lib/rules/no-get.js
Labels: Breaking, Enhancement

#731 Enable additional `recommended` rules
  README.md
  lib/octane-rules.js
  lib/recommended-rules.js
  lib/rules/no-empty-attrs.js
  lib/rules/no-get-with-default.js
  lib/rules/no-get.js
  lib/rules/no-incorrect-computed-macros.js
  lib/rules/no-invalid-dependent-keys.js
  lib/rules/no-jquery.js
  lib/rules/no-legacy-test-waiters.js
  lib/rules/no-mixins.js
  lib/rules/no-pause-test.js
  lib/rules/no-private-routing-service.js
  lib/rules/no-test-and-then.js
  lib/rules/no-test-import-export.js
  lib/rules/no-test-module-for.js
  lib/rules/require-computed-macros.js
  lib/rules/require-computed-property-dependencies.js
  lib/rules/use-ember-data-rfc-395-imports.js
  tests/__snapshots__/recommended.js.snap
Labels: Breaking, Enhancement

#730 Drop Node 8, 9, and 11 support
  .github/workflows/ci.yml
  README.md
  package.json
Labels: Breaking, Enhancement

#745 Replace `this.get('property')` with `this.property` in rule examples
  docs/rules/avoid-leaking-state-in-ember-objects.md
  docs/rules/no-attrs-in-components.md
  docs/rules/no-mixins.md
  docs/rules/no-new-mixins.md
  docs/rules/no-side-effects.md
  docs/rules/order-in-components.md
  docs/rules/order-in-controllers.md
  docs/rules/order-in-models.md
  docs/rules/order-in-routes.md
  docs/rules/require-return-from-computed.md
Labels: Documentation

#746 Remove non-recommended rules from cluttering `recommended-rules.js`
  lib/recommended-rules.js
  scripts/update-rules.js
  tests/rule-setup.js
Labels: Internal

#748 Switch to new module imports in rule examples
  docs/rules/computed-property-getters.md
  docs/rules/jquery-ember-run.md
  docs/rules/no-attrs-snapshot.md
  docs/rules/no-computed-properties-in-native-classes.md
  docs/rules/no-ember-testing-in-module-scope.md
  docs/rules/no-observers.md
  docs/rules/no-side-effects.md
  docs/rules/require-super-in-init.md
Labels: Documentation

#749 Add missing init hook super calls in rule examples
  docs/rules/no-ember-testing-in-module-scope.md
  docs/rules/no-global-jquery.md
  docs/rules/no-legacy-test-waiters.md
Labels: Documentation

#747 Add autofixer to `no-get-with-default` rule
  README.md
  docs/rules/no-get-with-default.md
  lib/rules/no-get-with-default.js
  tests/lib/rules/no-get-with-default.js
Labels: Enhancement
