Repository ember-cli/eslint-plugin-ember, pull requests merged in 2020-09, with the labels that each got.

#928 Refactor `require-super-in-init` rule to improve performance
  lib/rules/require-super-in-init.js
Labels: Bug

#929 Fix spread syntax crash in `avoid-using-needs-in-controllers` rule
  lib/rules/avoid-using-needs-in-controllers.js
  tests/lib/rules/avoid-using-needs-in-controllers.js
Labels: Bug

#931 Fix spread syntax crash in `no-unnecessary-route-path-option` rule
  lib/rules/no-unnecessary-route-path-option.js
  tests/lib/rules/no-unnecessary-route-path-option.js
Labels: Bug

#930 Fix spread syntax crash in `no-restricted-resolver-tests` rule
  lib/rules/no-restricted-resolver-tests.js
  tests/lib/rules/no-restricted-resolver-tests.js
Labels: Bug

#932 Fix spread syntax crash in `route-path-style` rule
  lib/rules/route-path-style.js
  tests/lib/rules/route-path-style.js
Labels: Bug

#933 Fix spread syntax crash in `routes-segments-snake-case` rule
  lib/rules/routes-segments-snake-case.js
  tests/lib/rules/routes-segments-snake-case.js
Labels: Bug

#935 Add some more spread syntax tests
  tests/lib/rules/classic-decorator-hooks.js
  tests/lib/rules/new-module-imports.js
  tests/lib/rules/no-attrs-snapshot.js
  tests/lib/rules/no-unnecessary-service-injection-argument.js
  tests/lib/rules/use-ember-data-rfc-395-imports.js
Labels: Internal

#934 Fix spread syntax crashes in `order-in-*` rules
  docs/rules/order-in-components.md
  docs/rules/order-in-controllers.md
  docs/rules/order-in-models.md
  docs/rules/order-in-routes.md
  lib/rules/order-in-components.js
  lib/rules/order-in-controllers.js
  lib/rules/order-in-models.js
  lib/rules/order-in-routes.js
  lib/utils/ember.js
  lib/utils/property-order.js
  lib/utils/types.js
  tests/lib/rules/order-in-components.js
  tests/lib/rules/order-in-controllers.js
  tests/lib/rules/order-in-models.js
  tests/lib/rules/order-in-routes.js
  tests/lib/utils/property-order-test.js
Labels: Bug

#936 Add dependabot configuration
  .github/dependabot.yml
Labels: Internal

#938 Drop Node 13 support
  .github/workflows/ci.yml
  README.md
  package.json
Labels: Breaking

#939 Drop ESLint 5 support and add peer dependency on ESLint 6+
  .github/workflows/ci.yml
  README.md
  lib/utils/traverser.js
  package.json
Labels: Breaking

#941 Enable `catchRouterMicrolib` and `catchRouterMain` options in `no-private-routing-service rule` rule
  docs/rules/no-private-routing-service.md
  lib/rules/no-private-routing-service.js
  tests/lib/rules/no-private-routing-service.js
Labels: Breaking

#942 Enable `catchSafeObjects` option in `no-get` rule
  docs/rules/no-get.md
  lib/rules/no-get.js
  tests/lib/rules/no-get.js
Labels: Breaking

#943 Enable `catchEvents` option in `no-side-effects` rule
  docs/rules/no-side-effects.md
  lib/rules/no-side-effects.js
  tests/lib/rules/no-side-effects.js
Labels: Breaking

#940 Enable additional recommended rules
  README.md
  docs/rules/no-assignment-of-untracked-properties-used-in-tracking-contexts.md
  docs/rules/no-controller-access-in-routes.md
  docs/rules/no-invalid-test-waiters.md
  docs/rules/no-noop-setup-on-error-in-before.md
  docs/rules/no-test-this-render.md
  docs/rules/prefer-ember-test-helpers.md
  lib/recommended-rules.js
  lib/rules/no-assignment-of-untracked-properties-used-in-tracking-contexts.js
  lib/rules/no-controller-access-in-routes.js
  lib/rules/no-invalid-test-waiters.js
  lib/rules/no-noop-setup-on-error-in-before.js
  lib/rules/no-test-this-render.js
  lib/rules/prefer-ember-test-helpers.js
  tests/__snapshots__/recommended.js.snap
Labels: Breaking

#944 Ensure rule doc notices are present in the correct order
  tests/rule-setup.js
Labels: Internal

#945 Add sort-package-json
  .npmpackagejsonlintrc.json
  package.json
  yarn.lock
Labels: Internal

#950 Add autofixer to `require-super-in-init` rule
  README.md
  docs/rules/require-super-in-init.md
  lib/rules/require-super-in-init.js
  tests/lib/rules/require-super-in-init.js
Labels: Enhancement

#956 Add imports in `no-test-module-for` rule doc
  docs/rules/no-test-module-for.md
Labels: Documentation

#957 Add `checkInitOnly` (default true) and `checkNativeClasses` (default false) options to `require-super-in-init` rule
  README.md
  docs/rules/require-super-in-init.md
  lib/rules/require-super-in-init.js
  tests/lib/rules/require-super-in-init.js
Labels: Enhancement

#961 Add `checkPlainGetters` option (default false) to `no-side-effects` rule
  docs/rules/no-side-effects.md
  lib/rules/no-side-effects.js
  tests/lib/rules/no-side-effects.js
Labels: Enhancement

#962 Do not pass `...arguments` in autofix for attrs hooks in `require-super-in-init` rule
  lib/rules/require-super-in-init.js
  tests/lib/rules/require-super-in-init.js
Labels: Bug

#966 Add new rule `no-test-support-import`
  README.md
  docs/rules/no-test-support-import.md
  lib/index.js
  lib/rules/no-test-support-import.js
  tests/lib/rules/no-test-support-import.js
Labels: Enhancement
