Repository ember-cli/eslint-plugin-ember, pull requests merged in 2020-04, with the labels that each got.

#755 Add note about nullish coalescing operator in `no-get-with-default` rule doc
  docs/rules/no-get-with-default.md
Labels: Documentation

#752 Remove `no-empty-attrs` from `recommended` config
  README.md
  lib/recommended-rules.js
  lib/rules/no-empty-attrs.js
  tests/__snapshots__/recommended.js.snap
Labels: Bug

#757 Add tests that configs are exported and mentioned in the README
  lib/index.js
  tests/config-setup.js
Labels: Internal

#758 Fix typo in example in `no-side-effects` rule doc
  docs/rules/no-side-effects.md
Labels: Documentation

#759 Update each rule doc to mention what config enables the rule
  docs/rules/_TEMPLATE_.md
  docs/rules/avoid-leaking-state-in-ember-objects.md
  docs/rules/avoid-using-needs-in-controllers.md
  docs/rules/classic-decorator-hooks.md
  docs/rules/classic-decorator-no-classic-methods.md
  docs/rules/closure-actions.md
  docs/rules/jquery-ember-run.md
  docs/rules/new-module-imports.md
  docs/rules/no-actions-hash.md
  docs/rules/no-arrow-function-computed-properties.md
  docs/rules/no-attrs-in-components.md
  docs/rules/no-attrs-snapshot.md
  docs/rules/no-capital-letters-in-routes.md
  docs/rules/no-classic-classes.md
  docs/rules/no-classic-components.md
  docs/rules/no-component-lifecycle-hooks.md
  docs/rules/no-computed-properties-in-native-classes.md
  docs/rules/no-deeply-nested-dependent-keys-with-each.md
  docs/rules/no-duplicate-dependent-keys.md
  docs/rules/no-ember-super-in-es-classes.md
  docs/rules/no-ember-testing-in-module-scope.md
  docs/rules/no-function-prototype-extensions.md
  docs/rules/no-get-with-default.md
  docs/rules/no-get.md
  docs/rules/no-global-jquery.md
  docs/rules/no-incorrect-calls-with-inline-anonymous-functions.md
  docs/rules/no-incorrect-computed-macros.md
  docs/rules/no-invalid-debug-function-arguments.md
  docs/rules/no-invalid-dependent-keys.md
  docs/rules/no-jquery.md
  docs/rules/no-legacy-test-waiters.md
  docs/rules/no-mixins.md
  docs/rules/no-new-mixins.md
  docs/rules/no-observers.md
  docs/rules/no-old-shims.md
  docs/rules/no-on-calls-in-components.md
  docs/rules/no-pause-test.md
  docs/rules/no-private-routing-service.md
  docs/rules/no-restricted-resolver-tests.md
  docs/rules/no-side-effects.md
  docs/rules/no-test-and-then.md
  docs/rules/no-test-import-export.md
  docs/rules/no-test-module-for.md
  docs/rules/no-unnecessary-route-path-option.md
  docs/rules/no-volatile-computed-properties.md
  docs/rules/require-computed-macros.md
  docs/rules/require-computed-property-dependencies.md
  docs/rules/require-return-from-computed.md
  docs/rules/require-super-in-init.md
  docs/rules/require-tagless-components.md
  docs/rules/routes-segments-snake-case.md
  docs/rules/use-brace-expansion.md
  docs/rules/use-ember-data-rfc-395-imports.md
  tests/rule-setup.js
Labels: Documentation

#764 Catch unnecessary braces in `no-invalid-dependent-keys` rule
  docs/rules/no-invalid-dependent-keys.md
  lib/rules/no-invalid-dependent-keys.js
  tests/lib/rules/no-invalid-dependent-keys.js
Labels: Enhancement

#766 Add test for `no-replace-test-comments` rule with TODO-prefixed comment
  tests/lib/rules/no-replace-test-comments.js
Labels: Internal

#771 Fix false positives in `no-legacy-test-waiters` rule
  lib/rules/no-legacy-test-waiters.js
  tests/lib/rules/no-legacy-test-waiters.js
Labels: Bug

#768 Catch leading or trailing periods in `no-invalid-dependent-keys`
  docs/rules/no-invalid-dependent-keys.md
  lib/rules/no-invalid-dependent-keys.js
  tests/lib/rules/no-invalid-dependent-keys.js
Labels: Enhancement

#773 Add autofixer to `no-duplicate-dependent-keys` rule
  README.md
  docs/rules/no-duplicate-dependent-keys.md
  lib/rules/no-duplicate-dependent-keys.js
  lib/rules/no-unnecessary-route-path-option.js
  lib/utils/fixer.js
  lib/utils/types.js
  lib/utils/utils.js
  tests/lib/rules/no-duplicate-dependent-keys.js
  tests/lib/rules/no-invalid-debug-function-arguments.js
  tests/lib/utils/utils-test.js
Labels: Enhancement

#774 Catch spaces in `no-invalid-dependent-keys` rule
  docs/rules/no-invalid-dependent-keys.md
  lib/rules/no-invalid-dependent-keys.js
  tests/lib/rules/no-invalid-dependent-keys.js
Labels: Enhancement

#775 Handle explicit getter functions in `require-computed-property-dependencies` rule
  lib/rules/require-computed-property-dependencies.js
  lib/utils/computed-properties.js
  tests/lib/rules/require-computed-property-dependencies.js
  tests/lib/utils/computed-properties-test.js
Labels: Enhancement

#779 Add decorator support to `require-computed-property-dependencies` rule
  docs/rules/require-computed-property-dependencies.md
  lib/rules/require-computed-property-dependencies.js
  lib/utils/computed-properties.js
  tests/lib/rules/require-computed-property-dependencies.js
Labels: Enhancement

#781 Add decorator support to `no-unnecessary-service-injection-argument` rule
  docs/rules/no-unnecessary-service-injection-argument.md
  lib/rules/no-unnecessary-service-injection-argument.js
  tests/lib/rules/no-unnecessary-service-injection-argument.js
Labels: Enhancement

#778 Add new rule `no-test-this-render`
  README.md
  docs/rules/no-test-this-render.md
  lib/index.js
  lib/rules/no-test-this-render.js
  tests/lib/rules/no-test-this-render.js
Labels: Enhancement

#786 Ignore the left side of an assignment in `require-computed-property-dependencies` rule
  lib/rules/require-computed-property-dependencies.js
  lib/utils/types.js
  tests/lib/rules/require-computed-property-dependencies.js
Labels: Bug

#767 Add new rule `prefer-ember-test-helpers`
  README.md
  docs/rules/prefer-ember-test-helpers.md
  lib/index.js
  lib/rules/prefer-ember-test-helpers.js
  tests/lib/rules/prefer-ember-test-helpers.js
Labels: Enhancement

#789 Add decorator support to `no-side-effects` rule
  docs/rules/no-side-effects.md
  lib/rules/no-side-effects.js
  lib/rules/require-computed-property-dependencies.js
  lib/utils/traverser.js
  tests/lib/rules/no-side-effects.js
Labels: Enhancement

#790 Catch assignment in `no-side-effects` rule
  docs/rules/no-side-effects.md
  lib/rules/no-side-effects.js
  tests/lib/rules/no-side-effects.js
Labels: Enhancement

#794 Handle braces without nesting in `require-computed-property-dependencies` rule
  lib/utils/computed-property-dependent-keys.js
  tests/lib/rules/require-computed-property-dependencies.js
  tests/lib/utils/computed-property-dependent-keys-test.js
Labels: Bug

#797 Remove duplicate example from `no-observers` rule doc
  docs/rules/no-observers.md
Labels: Documentation

#801 Begin testing under Node 14
  .github/workflows/ci.yml
Labels: Internal

#800 Handle `@computed` decorator without parentheses in `no-side-effects` and `require-computed-property-dependencies` rules
  lib/rules/no-side-effects.js
  lib/rules/require-computed-property-dependencies.js
  lib/utils/computed-properties.js
  lib/utils/ember.js
  tests/lib/rules/no-side-effects.js
  tests/lib/rules/require-computed-property-dependencies.js
  tests/lib/rules/require-return-from-computed.js
  tests/lib/utils/ember-test.js
Labels: Bug
