Repository ember-cli/eslint-plugin-ember, pull requests merged in 2020-06, with the labels that each got.

#826 Update `no-computed-properties-in-native-classes` rule to ignore classes marked `@classic`
  docs/rules/no-computed-properties-in-native-classes.md
  lib/rules/no-computed-properties-in-native-classes.js
  lib/utils/types.js
  tests/lib/rules/no-computed-properties-in-native-classes.js
  tests/lib/utils/types-test.js
Labels: Enhancement

#828 Ensure rule docs mention all rule configuration options
  docs/rules/computed-property-getters.md
  tests/rule-setup.js
Labels: Internal

#827 Add new rule `no-restricted-service-injections`
  README.md
  docs/rules/no-restricted-service-injections.md
  lib/index.js
  lib/rules/no-restricted-service-injections.js
  package.json
  tests/lib/rules/no-restricted-service-injections.js
  yarn.lock
Labels: Enhancement

#839 Support `filterBy` and `mapBy` macros in `require-computed-macros` rule
  docs/rules/require-computed-macros.md
  lib/rules/require-computed-macros.js
  tests/lib/rules/require-computed-macros.js
Labels: Enhancement

#842 Explain why `require-return-from-computed` rule does not apply to native classes
  docs/rules/require-return-from-computed.md
  tests/lib/rules/require-return-from-computed.js
Labels: Documentation

#840 Add `includeNativeGetters` option (default false) to `require-computed-macros` rule
  docs/rules/require-computed-macros.md
  lib/rules/require-computed-macros.js
  tests/lib/rules/require-computed-macros.js
Labels: Enhancement

#846 Support optional chaining in `require-computed-macros` rule
  lib/utils/property-getter.js
  lib/utils/types.js
  tests/lib/rules/require-computed-macros.js
  tests/lib/utils/property-getter-test.js
Labels: Enhancement

#848 Add optional chaining support to `require-computed-property-dependencies` rule
  lib/rules/require-computed-property-dependencies.js
  lib/utils/property-getter.js
  lib/utils/types.js
  tests/lib/rules/require-computed-macros.js
  tests/lib/rules/require-computed-property-dependencies.js
Labels: Enhancement

#845 Add `useOptionalChaining` option (default false) to `no-get` rule
  docs/rules/no-get.md
  lib/rules/no-get.js
  tests/lib/rules/no-get.js
Labels: Enhancement

#856 Handle nested paths with ES5 setters in `no-side-effects` rule
  lib/rules/no-side-effects.js
  lib/utils/property-setter.js
  tests/lib/rules/no-side-effects.js
  tests/lib/utils/property-setter-test.js
Labels: Bug

#857 Ignore the left side of an assignment (nested path case) in `require-computed-property-dependencies` rule
  lib/rules/require-computed-property-dependencies.js
  tests/lib/rules/require-computed-property-dependencies.js
Labels: Bug

#864 Fix default value of `ignoreClassic` option to be true for `no-computed-properties-in-native-classes` rule
  lib/rules/no-computed-properties-in-native-classes.js
  tests/lib/rules/no-computed-properties-in-native-classes.js
Labels: Bug

#866 Fix missing import statement in autofix for `no-incorrect-computed-macros` rule
  lib/rules/no-incorrect-computed-macros.js
  tests/lib/rules/no-incorrect-computed-macros.js
Labels: Bug

#855 Add new rule `no-assignment-of-untracked-properties-used-in-tracking-contexts`
  README.md
  docs/rules/no-assignment-of-untracked-properties-used-in-tracking-contexts.md
  lib/index.js
  lib/rules/no-assignment-of-untracked-properties-used-in-tracking-contexts.js
  lib/utils/ember.js
  tests/lib/rules/no-assignment-of-untracked-properties-used-in-tracking-contexts.js
  tests/lib/utils/ember-test.js
Labels: Enhancement

#868 Fix false negatives in `no-invalid-test-waiters` rule
  lib/rules/no-invalid-test-waiters.js
  tests/lib/rules/no-invalid-test-waiters.js
Labels: Bug

#870 Fix false positive involving `this` keyword with `filterBy` / `mapBy` in `require-computed-macros` rule
  lib/rules/require-computed-macros.js
  lib/utils/scope-references-this.js
  tests/lib/rules/require-computed-macros.js
  tests/lib/utils/scope-references-this-test.js
Labels: Bug

#871 Add `catchRouterMain` option to `no-private-routing-service` rule
  docs/rules/no-private-routing-service.md
  lib/rules/no-private-routing-service.js
  tests/lib/rules/no-private-routing-service.js
Labels: Enhancement
