Repository ember-cli/eslint-plugin-ember, pull requests merged in 2020-05, with the labels that each got.

#802 Ignore `mirage/config.js` file in `no-get` rule
  docs/rules/no-get.md
  lib/rules/no-get.js
  lib/rules/use-ember-get-and-set.js
  lib/utils/ember.js
  tests/lib/rules/no-get.js
  tests/lib/utils/ember-test.js
Labels: Bug

#795 Disallow accessing `_routerMicrolib` in `no-private-routing-service` rule
  docs/rules/no-private-routing-service.md
  lib/rules/no-private-routing-service.js
  tests/lib/rules/no-private-routing-service.js
Labels: Enhancement

#812 Fix false negative when aliasing import in `prefer-ember-test-helpers` rule
  lib/rules/prefer-ember-test-helpers.js
  tests/lib/rules/prefer-ember-test-helpers.js
Labels: Bug

#813 Fix false positive with multiple imports in `prefer-ember-test-helpers` rule
  lib/rules/prefer-ember-test-helpers.js
  tests/lib/rules/prefer-ember-test-helpers.js
Labels: Bug

#814 Upgrade to eslint 7 internally
  .eslintrc.js
  .github/workflows/ci.yml
  lib/utils/property-order.js
  package.json
  tests/lib/rules/order-in-components.js
  tests/lib/rules/order-in-controllers.js
  tests/lib/rules/order-in-models.js
  tests/lib/rules/order-in-routes.js
  yarn.lock
Labels: Internal

#823 Include recommended fix in `no-ember-super-in-es-classes` rule error message
  lib/rules/no-ember-super-in-es-classes.js
  tests/lib/rules/no-ember-super-in-es-classes.js
Labels: Documentation

#821 Avoid some false positives when detecting if a file is an Ember component, controller, etc
  lib/utils/ember.js
  tests/lib/utils/ember-test.js
Labels: Bug
