Repository ember-cli/eslint-plugin-ember, pull requests merged in 2020-01, with the labels that each got.

#640 Update `no-computed-properties-in-native-classes` rule to catch aliasing of computed import
  lib/rules/no-computed-properties-in-native-classes.js
  tests/lib/rules/no-computed-properties-in-native-classes.js
Labels: Bug

#639 Update `no-observers` rule to catch `addObserver` and observer imports
  docs/rules/no-observers.md
  lib/rules/no-classic-classes.js
  lib/rules/no-observers.js
  tests/lib/rules/no-observers.js
Labels: Enhancement

#643 Add missing test case output assertions
  .eslintrc.js
  tests/lib/rules/classic-decorator-hooks.js
  tests/lib/rules/classic-decorator-no-classic-methods.js
  tests/lib/rules/no-actions-hash.js
  tests/lib/rules/no-arrow-function-computed-properties.js
  tests/lib/rules/no-classic-classes.js
  tests/lib/rules/no-classic-components.js
  tests/lib/rules/no-incorrect-calls-with-inline-anonymous-functions.js
  tests/lib/rules/no-unnecessary-index-route.js
  tests/lib/rules/no-volatile-computed-properties.js
  tests/lib/rules/require-return-from-computed.js
  tests/lib/rules/route-path-style.js
  tests/lib/rules/use-ember-data-rfc-395-imports.js
Labels: Internal

#648 Fix various spelling mistakes
  docs/rules/new-module-imports.md
  docs/rules/no-attrs-snapshot.md
  docs/rules/order-in-controllers.md
  lib/rules/use-ember-data-rfc-395-imports.js
  lib/utils/import.js
  lib/utils/utils.js
  tests/lib/rules/no-on-calls-in-components.js
  tests/lib/rules/no-test-module-for.js
  tests/lib/rules/order-in-controllers.js
  tests/lib/utils/ember-test.js
Labels: Documentation

#646 Fix crash with default imports in `no-observers` and `no-computed-properties-in-native-classes` rules
  lib/rules/no-computed-properties-in-native-classes.js
  lib/rules/no-observers.js
  tests/lib/rules/no-computed-properties-in-native-classes.js
  tests/lib/rules/no-observers.js
Labels: Bug
