Repository ember-cli/eslint-plugin-ember, pull requests merged in 2020-12, with the labels that each got.

#1018 Update `checkInitOnly` option default to false in `require-super-init` rule
  docs/rules/require-super-in-init.md
  lib/rules/require-super-in-init.js
  tests/lib/rules/require-super-in-init.js
Labels: Breaking

#1019 Update `checkNativeClasses` option default to true in `require-super-in-init` rule
  docs/rules/require-super-in-init.md
  lib/rules/require-super-in-init.js
  tests/lib/rules/require-super-in-init.js
Labels: Breaking

#1020 Rename `require-super-in-init` rule to `require-super-in-lifecycle-hooks`
  CHANGELOG.md
  README.md
  docs/rules/require-super-in-lifecycle-hooks.md
  lib/index.js
  lib/recommended-rules.js
  lib/rules/require-super-in-lifecycle-hooks.js
  tests/__snapshots__/recommended.js.snap
  tests/lib/rules/require-super-in-lifecycle-hooks.js
Labels: Breaking

#1021 Update `checkPlainGetters` option default to true in `no-side-effects` rule
  docs/rules/no-side-effects.md
  lib/rules/no-side-effects.js
  tests/lib/rules/no-side-effects.js
Labels: Breaking

#1022 Update `checkSafeObjects` option default to true in `no-get-with-default` rule
  docs/rules/no-get-with-default.md
  lib/rules/no-get-with-default.js
  tests/lib/rules/no-get-with-default.js
Labels: Breaking

#1023 Update `checkUnsafeObjects` option default to true in `no-get-with-default` rule
  docs/rules/no-get-with-default.md
  lib/rules/no-get-with-default.js
  tests/lib/rules/no-get-with-default.js
Labels: Breaking

#1024 Enable additional `recommended` rules for v10
  README.md
  docs/rules/no-empty-glimmer-component-classes.md
  docs/rules/no-settled-after-test-helper.md
  docs/rules/no-shadow-route-definition.md
  docs/rules/no-string-prototype-extensions.md
  docs/rules/no-test-support-import.md
  docs/rules/no-try-invoke.md
  docs/rules/require-valid-css-selector-in-test-helpers.md
  lib/recommended-rules.js
  lib/rules/no-empty-glimmer-component-classes.js
  lib/rules/no-settled-after-test-helper.js
  lib/rules/no-shadow-route-definition.js
  lib/rules/no-string-prototype-extensions.js
  lib/rules/no-test-support-import.js
  lib/rules/no-try-invoke.js
  lib/rules/require-valid-css-selector-in-test-helpers.js
  tests/__snapshots__/recommended.js.snap
Labels: Breaking

#1025 Promote `octane` rules to `recommended` config and delete `octane` config
  .eslintignore
  .prettierignore
  README.md
  docs/rules/classic-decorator-hooks.md
  docs/rules/classic-decorator-no-classic-methods.md
  docs/rules/no-actions-hash.md
  docs/rules/no-classic-classes.md
  docs/rules/no-classic-components.md
  docs/rules/no-component-lifecycle-hooks.md
  docs/rules/no-computed-properties-in-native-classes.md
  docs/rules/require-tagless-components.md
  lib/config/octane.js
  lib/index.js
  lib/octane-rules.js
  lib/recommended-rules.js
  lib/rules/classic-decorator-hooks.js
  lib/rules/classic-decorator-no-classic-methods.js
  lib/rules/no-actions-hash.js
  lib/rules/no-classic-classes.js
  lib/rules/no-classic-components.js
  lib/rules/no-component-lifecycle-hooks.js
  lib/rules/no-computed-properties-in-native-classes.js
  lib/rules/require-tagless-components.js
  scripts/update-rules.js
  tests/__snapshots__/recommended.js.snap
  tests/plugin-exports.js
  tests/rule-setup.js
Labels: Breaking

#1027 no-settled-after-test-helper: Add missing node type check in `isAwaitSettlingTestHelper()`
  lib/rules/no-settled-after-test-helper.js
  tests/lib/rules/no-settled-after-test-helper.js
Labels: Bug

#1028 Mention Ember 3.13 minimum version to use tracked properties and Glimmer components in some rule docs
  docs/rules/no-classic-components.md
  docs/rules/no-computed-properties-in-native-classes.md
Labels: Documentation

#1030 Allow using string functions directly from Ember in `no-string-prototype-extensions` rule
  lib/rules/no-string-prototype-extensions.js
  tests/lib/rules/no-string-prototype-extensions.js
Labels: Bug

#1029 Handle comma-separated selectors in `require-valid-css-selector-in-test-helpers` rule
  lib/rules/require-valid-css-selector-in-test-helpers.js
  tests/lib/rules/require-valid-css-selector-in-test-helpers.js
Labels: Bug

#1036 Catch `willDestroy` Glimmer component hook in `require-super-in-life-cycle-hooks` rule
  lib/rules/require-super-in-lifecycle-hooks.js
  tests/lib/rules/require-super-in-lifecycle-hooks.js
Labels: Bug

#1043 Fix false positive in `no-shadow-route-definition` rule
  lib/rules/no-shadow-route-definition.js
  tests/lib/rules/no-shadow-route-definition.js
Labels: Bug

#1038 Improve detection of global window methods in `prefer-ember-test-helpers` rule
  lib/rules/prefer-ember-test-helpers.js
  package.json
  tests/lib/rules/prefer-ember-test-helpers.js
Labels: Bug

#1051 Fix path checks for Windows in `no-test-import-export` and `no-test-support-import` rules
  lib/rules/no-test-import-export.js
  lib/rules/no-test-support-import.js
  lib/utils/ember.js
Labels: Bug

#1052 Add Windows to CI testing matrix
  .gitattributes
  .github/workflows/ci.yml
  package.json
Labels: Internal

#1054 Handle commas inside quotes in selectors in `require-valid-css-selector-in-test-helpers` rule
  lib/rules/require-valid-css-selector-in-test-helpers.js
  tests/lib/rules/require-valid-css-selector-in-test-helpers.js
Labels: Bug

#1055 Implement `require-fetch-import` rule
  README.md
  docs/rules/require-fetch-import.md
  lib/index.js
  lib/rules/require-fetch-import.js
  tests/lib/rules/require-fetch-import.js
Labels: Enhancement

#1056 Implement `no-current-route-name` rule
  README.md
  docs/rules/no-current-route-name.md
  lib/index.js
  lib/rules/no-current-route-name.js
  tests/lib/rules/no-current-route-name.js
Labels: Enhancement

#1040 `willDestroy` should be considered a classic component lifecycle hook in `require-super-in-lifecycle-hooks` and `no-component-lifecycle-hooks` rules
  docs/rules/no-component-lifecycle-hooks.md
  lib/rules/no-component-lifecycle-hooks.js
  lib/rules/require-super-in-lifecycle-hooks.js
  lib/utils/ember.js
  tests/lib/rules/no-component-lifecycle-hooks.js
  tests/lib/rules/require-super-in-lifecycle-hooks.js
Labels: Bug

#1059 no-component-lifecycle-hooks: Do not warn about Glimmer lifecycle hooks on classic components
  docs/rules/no-component-lifecycle-hooks.md
  lib/rules/no-component-lifecycle-hooks.js
  tests/lib/rules/no-component-lifecycle-hooks.js
Labels: Bug

#1060 Automate release process with release-it-lerna-changelog
  RELEASE.md
  package.json
  yarn.lock
Labels: Internal
