Repository ember-cli/eslint-plugin-ember, pull requests merged in 2020-11, with the labels that each got.

#998 Fix autofix for array element access at beginning of path string in `no-get` rule
  lib/rules/no-get.js
  tests/lib/rules/no-get.js
Labels: Bug

#993 Add new rule `no-empty-glimmer-component-classes`
  README.md
  docs/rules/no-empty-glimmer-component-classes.md
  lib/index.js
  lib/rules/no-empty-glimmer-component-classes.js
  tests/lib/rules/no-empty-glimmer-component-classes.js
Labels: Enhancement

#1000 Add `catchSafeObjects` and `catchUnsafeObjects` options (default false) to `no-get-with-default` rule
  docs/rules/no-get-with-default.md
  docs/rules/no-get.md
  lib/rules/no-get-with-default.js
  tests/lib/rules/no-get-with-default.js
Labels: Enhancement

#1001 Fix issues with `no-get` rule autofix with array access in nested path
  lib/rules/no-get.js
  tests/lib/rules/no-get.js
Labels: Bug

#1005 Fix typo in `require-valid-css-selector-in-test-helpers` rule doc
  docs/rules/require-valid-css-selector-in-test-helpers.md
Labels: Documentation

#1006 Elaborate on configuration in `avoid-leaking-state-in-ember-objects` rule doc
  docs/rules/avoid-leaking-state-in-ember-objects.md
Labels: Documentation
