Repository ember-cli/eslint-plugin-ember, pull requests merged in 2020-10, with the labels that each got.

#967 Avoid false positives and properly check imports in `no-observers` rule
  lib/rules/no-observers.js
  lib/utils/ember.js
  tests/lib/rules/no-observers.js
  tests/lib/utils/ember-test.js
Labels: Bug

#971 Handle path separators for different platforms in `no-test-support-import` rule
  lib/rules/no-test-support-import.js
Labels: Bug

#973 Add new rule `no-try-invoke`
  README.md
  docs/rules/no-try-invoke.md
  lib/index.js
  lib/rules/no-try-invoke.js
  tests/lib/rules/no-try-invoke.js
Labels: Enhancement

#986 Add new rule `no-string-prototype-extensions`
  README.md
  docs/rules/no-string-prototype-extensions.md
  lib/index.js
  lib/rules/no-string-prototype-extensions.js
  tests/lib/rules/no-string-prototype-extensions.js
Labels: Enhancement

#985 Add new rule `no-settled-after-test-helper`
  README.md
  docs/rules/no-settled-after-test-helper.md
  lib/index.js
  lib/rules/no-settled-after-test-helper.js
  tests/lib/rules/no-settled-after-test-helper.js
Labels: Enhancement

#978 Add new rule `no-shadow-route-definition`
  README.md
  docs/rules/no-shadow-route-definition.md
  lib/index.js
  lib/rules/no-shadow-route-definition.js
  tests/lib/rules/no-shadow-route-definition.js
Labels: Enhancement

#980 Add new rule `require-valid-css-selector-in-test-helpers`
  README.md
  docs/rules/require-valid-css-selector-in-test-helpers.md
  lib/index.js
  lib/rules/require-valid-css-selector-in-test-helpers.js
  package.json
  tests/lib/rules/require-valid-css-selector-in-test-helpers.js
  yarn.lock
Labels: Enhancement

#991 Add test to ensure rule test files have correct test suite name
  tests/lib/rules/no-incorrect-calls-with-inline-anonymous-functions.js
  tests/lib/rules/no-test-import-export.js
  tests/rule-setup.js
Labels: Internal
