Repository ember-cli/eslint-plugin-ember, pull requests merged in 2020-07, with the labels that each got.

#879 Autofix nested paths in the left side of an assignment without using optional chaining in the `no-get` rule
  lib/rules/no-get.js
  lib/rules/require-computed-property-dependencies.js
  lib/utils/utils.js
  tests/lib/rules/no-get.js
Labels: Bug

#880 Use imported name of `get` and `getProperties` in `no-get` rule
  lib/rules/no-get.js
  tests/lib/rules/no-get.js
Labels: Bug

#881 Check imports in `no-get-with-default` rule
  lib/rules/no-get-with-default.js
  tests/lib/rules/no-get-with-default.js
Labels: Bug

#882 Check imports in `no-pause-test` rule
  lib/rules/no-pause-test.js
  tests/lib/rules/no-pause-test.js
Labels: Bug

#883 Handle computed property macros in `no-assignment-of-untracked-properties-used-in-tracking-contexts` rule
  lib/rules/no-assignment-of-untracked-properties-used-in-tracking-contexts.js
  lib/utils/computed-property-dependent-keys.js
  lib/utils/computed-property-macros.js
  lib/utils/decorators.js
  lib/utils/utils.js
  tests/lib/rules/no-assignment-of-untracked-properties-used-in-tracking-contexts.js
  tests/lib/utils/computed-property-dependent-keys-test.js
  tests/lib/utils/computed-property-macros-test.js
  tests/lib/utils/decorators-test.js
  tests/lib/utils/utils-test.js
Labels: Bug

#888 Add npm-package-json-lint
  .npmpackagejsonlintrc.json
  package.json
  yarn.lock
Labels: Internal

#893 Support array element access in `no-get` rule autofix
  lib/rules/no-get.js
  tests/lib/rules/no-get.js
Labels: Bug

#894 Ensure `no-attrs-in-components` rule only runs inside components
  lib/rules/no-attrs-in-components.js
  tests/lib/rules/no-attrs-in-components.js
Labels: Bug

#895 Update `no-test-import-export` rule to allow importing from anything under `tests/helpers` path
  docs/rules/no-test-import-export.md
  lib/rules/no-test-import-export.js
  tests/lib/rules/no-test-import-export.js
Labels: Bug

#887 Add option for custom computed property macros in `no-assignment-of-untracked-properties-used-in-tracking-contexts` rule
  docs/rules/no-assignment-of-untracked-properties-used-in-tracking-contexts.md
  lib/rules/no-assignment-of-untracked-properties-used-in-tracking-contexts.js
  lib/utils/computed-property-dependent-keys.js
  lib/utils/computed-property-macros.js
  lib/utils/javascript.js
  tests/lib/rules/no-assignment-of-untracked-properties-used-in-tracking-contexts.js
  tests/lib/utils/computed-property-dependent-keys-test.js
  tests/lib/utils/computed-property-macros-test.js
Labels: Enhancement
