Repository ember-cli/eslint-plugin-ember, pull requests merged in 2021-05, with the labels that each got.

#1179 Handle both `babel-eslint` and `@babel/eslint-parser` spread syntax in `order-in-*` rules
  lib/utils/property-order.js
Labels: Bug

#1180 Switch from `babel-eslint` to `@babel/eslint-parser`
  .babelrc
  .eslintrc.js
  package.json
  tests/helpers/babel-eslint-parser.js
  tests/helpers/faux-context.js
  tests/lib/rules/avoid-leaking-state-in-ember-objects.js
  tests/lib/rules/avoid-using-needs-in-controllers.js
  tests/lib/rules/classic-decorator-hooks.js
  tests/lib/rules/classic-decorator-no-classic-methods.js
  tests/lib/rules/new-module-imports.js
  tests/lib/rules/no-actions-hash.js
  tests/lib/rules/no-assignment-of-untracked-properties-used-in-tracking-contexts.js
  tests/lib/rules/no-attrs-in-components.js
  tests/lib/rules/no-attrs-snapshot.js
  tests/lib/rules/no-computed-properties-in-native-classes.js
  tests/lib/rules/no-controller-access-in-routes.js
  tests/lib/rules/no-controllers.js
  tests/lib/rules/no-deeply-nested-dependent-keys-with-each.js
  tests/lib/rules/no-duplicate-dependent-keys.js
  tests/lib/rules/no-get.js
  tests/lib/rules/no-incorrect-computed-macros.js
  tests/lib/rules/no-invalid-dependent-keys.js
  tests/lib/rules/no-observers.js
  tests/lib/rules/no-private-routing-service.js
  tests/lib/rules/no-restricted-resolver-tests.js
  tests/lib/rules/no-restricted-service-injections.js
  tests/lib/rules/no-settled-after-test-helper.js
  tests/lib/rules/no-shadow-route-definition.js
  tests/lib/rules/no-side-effects.js
  tests/lib/rules/no-string-prototype-extensions.js
  tests/lib/rules/no-unnecessary-route-path-option.js
  tests/lib/rules/no-unnecessary-service-injection-argument.js
  tests/lib/rules/no-unused-services.js
  tests/lib/rules/no-volatile-computed-properties.js
  tests/lib/rules/order-in-components.js
  tests/lib/rules/order-in-controllers.js
  tests/lib/rules/order-in-models.js
  tests/lib/rules/order-in-routes.js
  tests/lib/rules/require-computed-macros.js
  tests/lib/rules/require-computed-property-dependencies.js
  tests/lib/rules/require-return-from-computed.js
  tests/lib/rules/require-super-in-lifecycle-hooks.js
  tests/lib/rules/require-tagless-components.js
  tests/lib/rules/route-path-style.js
  tests/lib/rules/routes-segments-snake-case.js
  tests/lib/rules/use-brace-expansion.js
  tests/lib/rules/use-ember-data-rfc-395-imports.js
  tests/lib/utils/computed-properties-test.js
  tests/lib/utils/computed-property-dependent-keys-test.js
  tests/lib/utils/decorators-test.js
  tests/lib/utils/ember-test.js
  tests/lib/utils/import-test.js
  tests/lib/utils/new-module-test.js
  tests/lib/utils/property-getter-test.js
  tests/lib/utils/property-setter-test.js
  tests/lib/utils/scope-references-this-test.js
  tests/lib/utils/types-test.js
  tests/lib/utils/utils-test.js
  tests/lib/utils/utils/get-source-module-name-for-identifier-test.js
  yarn.lock
Labels: Internal

#1187 Fix optional chaining support to handle newer ChainExpression implementation
  lib/rules/no-side-effects.js
  lib/utils/computed-property-dependent-keys.js
  lib/utils/property-getter.js
  lib/utils/utils.js
  tests/lib/rules/no-private-routing-service.js
  yarn.lock
Labels: Bug

#1191 Use `requireindex` to export rules and configs
  lib/index.js
  package.json
  yarn.lock
Labels: Internal

#1195 Fix false positives with service/controller/observer detection in some rules
  lib/utils/ember.js
  lib/utils/property-order.js
  tests/lib/utils/ember-test.js
  tests/lib/utils/property-order-test.js
Labels: Bug

#1196 Check import when detecting observer usage in `order-in-*` rules
  lib/rules/order-in-components.js
  lib/rules/order-in-controllers.js
  lib/rules/order-in-models.js
  lib/rules/order-in-routes.js
  lib/utils/ember.js
  lib/utils/property-order.js
  tests/lib/rules/order-in-components.js
  tests/lib/rules/order-in-controllers.js
  tests/lib/utils/ember-test.js
  tests/lib/utils/property-order-test.js
Labels: Bug

#1197 Check import when detecting controller usage in `order-in-*` rules
  lib/rules/order-in-components.js
  lib/rules/order-in-controllers.js
  lib/rules/order-in-models.js
  lib/rules/order-in-routes.js
  lib/utils/ember.js
  lib/utils/property-order.js
  tests/lib/rules/order-in-controllers.js
  tests/lib/utils/ember-test.js
  tests/lib/utils/property-order-test.js
Labels: Bug

#1204 Improve columns in README rules table
  README.md
  scripts/update-rules.js
Labels: Documentation

#1210 Avoid some false positives with lodash usage when recognizing extended Ember objects
  lib/utils/ember.js
  tests/lib/utils/ember-test.js
Labels: Bug

#1211 Fix false positive with non-components in `require-tagless-components` rule
  lib/rules/require-tagless-components.js
  tests/lib/rules/require-tagless-components.js
Labels: Bug

#1212 Improve detection of property names (check string literals in addition to identifiers) in several rules
  lib/rules/no-assignment-of-untracked-properties-used-in-tracking-contexts.js
  lib/rules/no-controllers.js
  lib/rules/no-restricted-service-injections.js
  lib/rules/no-unnecessary-service-injection-argument.js
  lib/rules/no-unused-services.js
  lib/rules/require-computed-property-dependencies.js
  tests/lib/rules/no-assignment-of-untracked-properties-used-in-tracking-contexts.js
  tests/lib/rules/no-controllers.js
  tests/lib/rules/no-restricted-service-injections.js
  tests/lib/rules/no-unnecessary-service-injection-argument.js
  tests/lib/rules/no-unused-services.js
  tests/lib/rules/require-computed-property-dependencies.js
Labels: Bug

#1194 Add new rule `no-restricted-property-modifications`
  README.md
  docs/rules/no-restricted-property-modifications.md
  lib/rules/no-restricted-property-modifications.js
  tests/lib/rules/no-restricted-property-modifications.js
Labels: Enhancement

#1213 Mention why some rules are not in the `recommended` config
  docs/rules/no-controllers.md
  docs/rules/no-empty-attrs.md
  docs/rules/no-html-safe.md
  docs/rules/no-proxies.md
  docs/rules/no-replace-test-comments.md
  docs/rules/no-unnecessary-service-injection-argument.md
  docs/rules/no-unused-services.md
  docs/rules/order-in-components.md
  docs/rules/order-in-controllers.md
  docs/rules/order-in-models.md
  docs/rules/order-in-routes.md
Labels: Documentation

#1188 Add new rule `no-implicit-service-injection-argument`
  README.md
  docs/rules/no-implicit-service-injection-argument.md
  docs/rules/no-unnecessary-service-injection-argument.md
  lib/rules/no-implicit-service-injection-argument.js
  lib/rules/no-restricted-service-injections.js
  lib/utils/ember.js
  tests/lib/rules/no-implicit-service-injection-argument.js
Labels: Enhancement
