Repository ember-cli/eslint-plugin-ember, pull requests merged in 2021-01, with the labels that each got.

#1066 Improve detection of globals in `no-global-jquery` rule
  lib/rules/no-global-jquery.js
  tests/lib/rules/no-global-jquery.js
Labels: Bug

#1063 Improve detection of globals and catch additional jQuery function calls in `no-jquery` rule
  lib/rules/no-global-jquery.js
  lib/rules/no-jquery.js
  lib/utils/jquery-methods.js
  lib/utils/utils.js
  package.json
  scripts/list-jquery-methods.js
  tests/lib/rules/no-global-jquery.js
  tests/lib/rules/no-jquery.js
  tests/lib/utils/utils-test.js
  yarn.lock
Labels: Bug

#1069 Improve tests for `jquery-ember-run` rule
  lib/rules/jquery-ember-run.js
  tests/lib/rules/jquery-ember-run.js
Labels: Internal

#1072 Improve jquery detection in `jquery-ember-run` rule
  lib/rules/jquery-ember-run.js
  lib/rules/no-global-jquery.js
  lib/rules/no-jquery.js
  lib/utils/jquery.js
  tests/lib/rules/jquery-ember-run.js
Labels: Bug

#1073 Allow any Ember runloop function in `jquery-ember-run` rule
  docs/rules/jquery-ember-run.md
  lib/rules/jquery-ember-run.js
  tests/lib/rules/jquery-ember-run.js
Labels: Bug

#1079 Add new rule `no-html-safe`
  README.md
  docs/rules/no-html-safe.md
  lib/index.js
  lib/rules/no-html-safe.js
  tests/lib/rules/no-html-safe.js
Labels: Enhancement
