Repository ember-cli/eslint-plugin-ember, pull requests merged in 2021-08, with the labels that each got.

#1275 Fix typo in `no-controller-access-in-routes` rule doc
  docs/rules/no-controller-access-in-routes.md
Labels: Documentation

#1277 Fix IIFE crash in `require-return-from-computed` rule
  lib/rules/require-return-from-computed.js
  tests/lib/rules/require-return-from-computed.js
Labels: Bug

#1280 Add CodeQL
  .github/workflows/codeql-analysis.yml
Labels: Internal

#1281 Catch destructured controller access in `no-controller-access-in-routes` rule
  lib/rules/no-controller-access-in-routes.js
  tests/lib/rules/no-controller-access-in-routes.js
Labels: Bug

#1283 Fix crash with `let foo` in `no-controller-access-in-routes`
  lib/rules/no-controller-access-in-routes.js
  tests/lib/rules/no-controller-access-in-routes.js
Labels: Bug

#1286 Avoid unnecessary optional chaining in autofix for `no-get` rule when using `useOptionalChaining` option
  lib/rules/no-get.js
  tests/lib/rules/no-get.js
Labels: Bug
