Repository ember-cli/eslint-plugin-ember, pull requests merged in 2021-09, with the labels that each got.

#1299 Cache dependencies on GitHub Actions to speed up CI
  .github/workflows/ci.yml
Labels: Internal

#1297 Support if/else route definitions in `no-shadow-route-definition` rule
  lib/rules/no-shadow-route-definition.js
  tests/lib/rules/no-shadow-route-definition.js
Labels: Bug

#1294 Super call missing arguments in some rule docs
  docs/rules/classic-decorator-hooks.md
  docs/rules/no-component-lifecycle-hooks.md
Labels: Documentation

#1300 Add `eslint-plugin` keywords in package.json
  package.json
Labels: Documentation
