Repository ember-cli/eslint-plugin-ember, pull requests merged in 2021-04, with the labels that each got.

#1127 Add automated suggestion to `route-path-style` rule for converting route path to kebab case
  lib/rules/route-path-style.js
  tests/lib/rules/route-path-style.js
Labels: Enhancement

#1132 Fix crash with dynamic/variable route name in `no-shadow-route-definition` rule (again)
  lib/rules/no-shadow-route-definition.js
  tests/lib/rules/no-shadow-route-definition.js
Labels: Bug

#1135 Fix false positive in same level routes but nested paths in `no-shadow-route-definition` rule
  lib/rules/no-shadow-route-definition.js
  tests/lib/rules/no-shadow-route-definition.js
Labels: Bug

#1149 Detect classic classes which have object variables passed to them in `no-classic-classes` rule
  lib/rules/no-classic-classes.js
  tests/lib/rules/no-classic-classes.js
Labels: Bug

#1150 `no-get` rule should ignore proxy classes that look like `ObjectProxy.extend(SomeMixin)`
  lib/utils/ember.js
  tests/lib/rules/no-get.js
  tests/lib/utils/ember-test.js
Labels: Bug

#1143 Add new rule `no-unused-services`
  README.md
  docs/rules/no-unused-services.md
  lib/index.js
  lib/rules/no-unnecessary-service-injection-argument.js
  lib/rules/no-unused-services.js
  lib/utils/computed-property-macros.js
  tests/lib/rules/no-unused-services.js
Labels: Enhancement

#1158 Improve robustness of classic class controller body detection in `no-controllers` rule
  lib/rules/no-classic-classes.js
  lib/rules/no-controllers.js
  lib/utils/utils.js
  tests/lib/rules/no-controllers.js
Labels: Bug

#1159 Improve robustness of classic class component body detection in `require-tagless-components` rule
  lib/rules/require-tagless-components.js
  tests/lib/rules/require-tagless-components.js
Labels: Bug

#1160 Account for observer dependent keys in `no-unused-services` rule
  lib/rules/no-unused-services.js
  tests/lib/rules/no-unused-services.js
Labels: Bug

#1161 Tweak messaging around false positives in `no-unused-services` rule
  docs/rules/no-unused-services.md
  lib/rules/no-unused-services.js
Labels: Documentation

#1162 Update several rules to check imports when checking for Ember service injections
  README.md
  lib/rules/no-private-routing-service.js
  lib/rules/no-restricted-service-injections.js
  lib/rules/no-unnecessary-service-injection-argument.js
  lib/rules/no-unused-services.js
  lib/rules/order-in-components.js
  lib/rules/order-in-controllers.js
  lib/rules/order-in-routes.js
  lib/rules/require-computed-property-dependencies.js
  lib/utils/ember.js
  lib/utils/property-order.js
  tests/lib/rules/no-private-routing-service.js
  tests/lib/rules/no-restricted-service-injections.js
  tests/lib/rules/no-unnecessary-service-injection-argument.js
  tests/lib/rules/no-unused-services.js
  tests/lib/rules/order-in-components.js
  tests/lib/rules/order-in-controllers.js
  tests/lib/rules/order-in-routes.js
  tests/lib/utils/ember-test.js
  tests/lib/utils/property-order-test.js
Labels: Bug

#1164 Account for `observes` decorator in `no-unused-services` rule
  lib/rules/no-unused-services.js
  tests/lib/rules/no-unused-services.js
Labels: Bug

#1165 Improve robustness of classic class body detection in several rules using `getModuleProperties` util
  lib/rules/alias-model-in-controller.js
  lib/rules/avoid-leaking-state-in-ember-objects.js
  lib/rules/avoid-using-needs-in-controllers.js
  lib/rules/no-actions-hash.js
  lib/rules/no-empty-attrs.js
  lib/rules/no-get.js
  lib/rules/no-on-calls-in-components.js
  lib/rules/order-in-components.js
  lib/rules/order-in-controllers.js
  lib/rules/order-in-models.js
  lib/rules/order-in-routes.js
  lib/utils/ember.js
  lib/utils/property-order.js
  tests/lib/rules/alias-model-in-controller.js
  tests/lib/rules/avoid-leaking-state-in-ember-objects.js
  tests/lib/rules/avoid-using-needs-in-controllers.js
  tests/lib/rules/no-actions-hash.js
  tests/lib/rules/no-empty-attrs.js
  tests/lib/rules/no-on-calls-in-components.js
  tests/lib/utils/ember-test.js
Labels: Bug

#1167 Update route rules to handle route path option passed as object variable
  lib/rules/no-shadow-route-definition.js
  lib/rules/no-unnecessary-route-path-option.js
  lib/rules/route-path-style.js
  lib/rules/routes-segments-snake-case.js
  tests/lib/rules/no-shadow-route-definition.js
  tests/lib/rules/no-unnecessary-route-path-option.js
  tests/lib/rules/route-path-style.js
  tests/lib/rules/routes-segments-snake-case.js
Labels: Bug

#1168 Avoid some false positives with jQuery usage when recognizing extended objects
  lib/utils/ember.js
  tests/lib/utils/ember-test.js
Labels: Bug
