Repository ember-cli/eslint-plugin-ember, pull requests merged in 2022-10, with the labels that each got.

#1582 Add link to deprecation RFC in `no-array-prototype-extensions` rule doc
  docs/rules/no-array-prototype-extensions.md
Labels: Documentation

#1601 Switch to dash for markdown lists
  .markdownlint.json
  docs/rules/_TEMPLATE_.md
  docs/rules/closure-actions.md
  docs/rules/computed-property-getters.md
  docs/rules/named-functions-in-promises.md
  docs/rules/no-array-prototype-extensions.md
  docs/rules/no-arrow-function-computed-properties.md
  docs/rules/no-assignment-of-untracked-properties-used-in-tracking-contexts.md
  docs/rules/no-attrs-in-components.md
  docs/rules/no-capital-letters-in-routes.md
  docs/rules/no-computed-properties-in-native-classes.md
  docs/rules/no-controller-access-in-routes.md
  docs/rules/no-current-route-name.md
  docs/rules/no-deeply-nested-dependent-keys-with-each.md
  docs/rules/no-function-prototype-extensions.md
  docs/rules/no-get.md
  docs/rules/no-html-safe.md
  docs/rules/no-implicit-service-injection-argument.md
  docs/rules/no-incorrect-computed-macros.md
  docs/rules/no-invalid-debug-function-arguments.md
  docs/rules/no-invalid-test-waiters.md
  docs/rules/no-mixins.md
  docs/rules/no-new-mixins.md
  docs/rules/no-observers.md
  docs/rules/no-pause-test.md
  docs/rules/no-private-routing-service.md
  docs/rules/no-proxies.md
  docs/rules/no-restricted-property-modifications.md
  docs/rules/no-restricted-service-injections.md
  docs/rules/no-settled-after-test-helper.md
  docs/rules/no-side-effects.md
  docs/rules/no-string-prototype-extensions.md
  docs/rules/no-test-and-then.md
  docs/rules/no-test-module-for.md
  docs/rules/no-test-support-import.md
  docs/rules/no-test-this-render.md
  docs/rules/no-unnecessary-index-route.md
  docs/rules/no-unnecessary-route-path-option.md
  docs/rules/no-unnecessary-service-injection-argument.md
  docs/rules/no-volatile-computed-properties.md
  docs/rules/prefer-ember-test-helpers.md
  docs/rules/require-computed-macros.md
  docs/rules/require-computed-property-dependencies.md
  docs/rules/require-fetch-import.md
  docs/rules/require-return-from-computed.md
  docs/rules/require-super-in-lifecycle-hooks.md
  docs/rules/require-tagless-components.md
  docs/rules/route-path-style.md
  docs/rules/routes-segments-snake-case.md
  docs/rules/use-ember-get-and-set.md
Labels: Documentation

#1609 Add `any` to `some` autofixer for `no-array-prototype-extensions` rule
  README.md
  docs/rules/no-array-prototype-extensions.md
  lib/rules/no-array-prototype-extensions.js
  tests/lib/rules/no-array-prototype-extensions.js
Labels: Enhancement

#1610 Add `filterBy` to `filter` autofixer for `no-array-prototype-extensions` rule
  lib/rules/no-array-prototype-extensions.js
  tests/lib/rules/no-array-prototype-extensions.js
Labels: Enhancement

#1611 Add `compact` to `filter` autofixer for `no-array-prototype-extensions` rule
  lib/rules/no-array-prototype-extensions.js
  tests/lib/rules/no-array-prototype-extensions.js
Labels: Enhancement

#1614 Add `findBy` to `find` autofixer for `no-array-prototype-extensions` rule
  lib/rules/no-array-prototype-extensions.js
  lib/utils/fixer.js
  tests/lib/rules/no-array-prototype-extensions.js
Labels: Enhancement

#1615 Add `objectAt` autofixer for `no-array-prototype-extensions rule`
  lib/rules/no-array-prototype-extensions.js
  tests/lib/rules/no-array-prototype-extensions.js
Labels: Enhancement

#1616 Add `toArray` autofixer for `no-array-prototype-extensions` rule
  lib/rules/no-array-prototype-extensions.js
  tests/lib/rules/no-array-prototype-extensions.js
Labels: Enhancement

#1617 Add `without` to `filter` autofixer for `no-array-prototype-extensions` rule
  lib/rules/no-array-prototype-extensions.js
  tests/lib/rules/no-array-prototype-extensions.js
Labels: Enhancement

#1618 Add jQuery codemod links
  docs/rules/jquery-ember-run.md
  docs/rules/no-global-jquery.md
  docs/rules/no-jquery.md
Labels: Documentation

#1619 Add `mapBy` to `map` autofixer for `no-array-prototype-extensions` rule
  lib/rules/no-array-prototype-extensions.js
  tests/lib/rules/no-array-prototype-extensions.js
Labels: Enhancement

#1620 Add `uniq` autofixer for `no-array-prototype-extensions` rule
  lib/rules/no-array-prototype-extensions.js
  tests/lib/rules/no-array-prototype-extensions.js
Labels: Enhancement

#1621 Add `sortBy` to `sort` autofixer for `no-array-prototype-extensions` rule
  lib/rules/no-array-prototype-extensions.js
  tests/lib/rules/no-array-prototype-extensions.js
Labels: Enhancement

#1626 Add `uniqBy` to `reduce` autofixer for `no-array-prototype-extensions` rule
  lib/rules/no-array-prototype-extensions.js
  tests/lib/rules/no-array-prototype-extensions.js
Labels: Enhancement

#1627 Add `rejectBy` to `filter` autofixer for `no-array-prototype-extensions` rule
  lib/rules/no-array-prototype-extensions.js
  tests/lib/rules/no-array-prototype-extensions.js
Labels: Enhancement

#1630 Add `isAny` and `isEvery` autofixers for `no-array-prototype-extensions` rule
  lib/rules/no-array-prototype-extensions.js
  tests/lib/rules/no-array-prototype-extensions.js
Labels: Enhancement

#1629 Add `reject` to `filter` autofixer for no-array-prototype-extensions rule
  lib/rules/no-array-prototype-extensions.js
  tests/lib/rules/no-array-prototype-extensions.js
Labels: Enhancement

#1631 Add `invoke` to `map` autofixer for `no-array-prototype-extensions` rule
  lib/rules/no-array-prototype-extensions.js
  tests/lib/rules/no-array-prototype-extensions.js
Labels: Enhancement

#1633 Add `setEach` to `forEach` autofixer for `no-array-prototype-extensions` rule
  lib/rules/no-array-prototype-extensions.js
  tests/lib/rules/no-array-prototype-extensions.js
Labels: Enhancement

#1635 Simpler autofix for `sortBy` with single arg for `no-array-prototype-extension` rule
  lib/rules/no-array-prototype-extensions.js
  tests/lib/rules/no-array-prototype-extensions.js
Labels: Bug

#1632 Add `getEach` to `map` autofixer for `no-array-prototype-extensions` rule
  lib/rules/no-array-prototype-extensions.js
  tests/lib/rules/no-array-prototype-extensions.js
Labels: Enhancement

#1639 Explain what the autofixer covers in `no-array-prototype-extensions` rule doc
  docs/rules/no-array-prototype-extensions.md
Labels: Documentation

#1395 Support `<template>` (no-undef, etc)
  lib/config/recommended.js
  lib/index.js
  lib/preprocessors/glimmer.js
  package.json
  tests/lib/rules-preprocessor/gjs-gts-processor-test.js
  yarn.lock
Labels: Enhancement

#1640 Avoid in-place sorting in `sortBy` autofixer in `no-array-prototype-extensions` rule
  lib/rules/no-array-prototype-extensions.js
  tests/lib/rules/no-array-prototype-extensions.js
Labels: Bug
