Repository ember-cli/eslint-plugin-ember, pull requests merged in 2022-07, with the labels that each got.

#1318 Drop support for Node 10, 12, 15, 17
  .github/workflows/ci.yml
  README.md
  lib/rules/no-duplicate-dependent-keys.js
  lib/rules/require-computed-property-dependencies.js
  lib/utils/computed-property-dependent-keys.js
  lib/utils/computed-property-macros.js
  lib/utils/ember.js
  lib/utils/javascript.js
  package.json
  tests/lib/rules/no-invalid-debug-function-arguments.js
  tests/lib/utils/javascript-test.js
  tests/rule-setup.js
Labels: Breaking

#1519 Enable `useOptionalChaining` option by default for `no-get` rule
  docs/rules/no-get.md
  lib/rules/no-get.js
  tests/lib/rules/no-get.js
Labels: Breaking

#1514 Strictly define Node API
  package.json
Labels: Breaking

#1512 Update `avoid-leaking-state-in-ember-objects` rule to augment instead of replace default config
  docs/rules/avoid-leaking-state-in-ember-objects.md
  lib/rules/avoid-leaking-state-in-ember-objects.js
  tests/lib/rules/avoid-leaking-state-in-ember-objects.js
Labels: Breaking

#1513 Stop exporting non-Ember utils
  lib/index.js
  tests/plugin-exports.js
Labels: Breaking

#1518 Remove `base` config
  README.md
  lib/config/base.js
  lib/config/recommended.js
  tests/config-setup.js
  tests/plugin-exports.js
Labels: Breaking

#1515 Drop support for ESLint v6
  .github/workflows/ci.yml
  README.md
  package.json
Labels: Breaking

#1529 Better support native class property definitions (and update to ESLint v8 internally)
  .eslintrc.js
  .github/workflows/ci.yml
  lib/rules/new-module-imports.js
  lib/rules/no-actions-hash.js
  lib/rules/no-assignment-of-untracked-properties-used-in-tracking-contexts.js
  lib/rules/no-controllers.js
  lib/rules/no-duplicate-dependent-keys.js
  lib/rules/no-implicit-service-injection-argument.js
  lib/rules/no-incorrect-calls-with-inline-anonymous-functions.js
  lib/rules/no-private-routing-service.js
  lib/rules/no-restricted-service-injections.js
  lib/rules/no-unnecessary-service-injection-argument.js
  lib/rules/no-unused-services.js
  lib/rules/require-tagless-components.js
  lib/rules/routes-segments-snake-case.js
  lib/rules/use-ember-data-rfc-395-imports.js
  lib/utils/decorators.js
  lib/utils/ember.js
  lib/utils/property-order.js
  lib/utils/types.js
  package.json
  scripts/update-rules.js
  tests/lib/rules/no-actions-hash.js
  tests/lib/rules/no-invalid-debug-function-arguments.js
  tests/lib/rules/no-private-routing-service.js
  tests/lib/rules/no-restricted-service-injections.js
  tests/lib/rules/no-shadow-route-definition.js
  tests/lib/rules/no-unused-services.js
  tests/lib/rules/require-tagless-components.js
  tests/lib/utils/computed-properties-test.js
  tests/lib/utils/computed-property-dependent-keys-test.js
  tests/lib/utils/computed-property-macros-test.js
  tests/lib/utils/decorators-test.js
  tests/lib/utils/ember-test.js
  tests/lib/utils/import-test.js
  tests/lib/utils/javascript-test.js
  tests/lib/utils/property-order-test.js
  tests/lib/utils/utils-test.js
  tests/lib/utils/utils/get-source-module-name-for-identifier-test.js
  tests/rule-setup.js
  yarn.lock
Labels: Bug

#1352 Upgrade ESLint dependencies and fix new linting issues
  .eslintrc.js
  lib/rules/new-module-imports.js
  lib/rules/no-classic-components.js
  lib/rules/no-controllers.js
  lib/rules/no-get-with-default.js
  lib/rules/no-get.js
  lib/rules/no-restricted-service-injections.js
  lib/rules/no-test-import-export.js
  lib/rules/no-test-module-for.js
  lib/rules/no-test-support-import.js
  lib/rules/require-computed-macros.js
  lib/rules/require-computed-property-dependencies.js
  lib/rules/use-ember-data-rfc-395-imports.js
  lib/utils/computed-properties.js
  lib/utils/computed-property-dependent-keys.js
  lib/utils/computed-property-macros.js
  lib/utils/decorators.js
  lib/utils/ember.js
  lib/utils/import.js
  package.json
  scripts/list-jquery-methods.js
  scripts/update-rules.js
  tests/config-setup.js
  tests/lib/rules/no-get.js
  tests/lib/rules/use-ember-get-and-set.js
  tests/rule-setup.js
  yarn.lock
Labels: Internal, dependencies

#1536 Ignore some commonly-known non-array functions/objects to reduce false positives in `no-array-prototype-extensions` rule
  lib/rules/no-array-prototype-extensions.js
  tests/lib/rules/no-array-prototype-extensions.js
Labels: Bug

#1539 Fix false positive with `RSVP.reject()` in `no-array-prototype-extensions`
  lib/rules/no-array-prototype-extensions.js
  tests/lib/rules/no-array-prototype-extensions.js
Labels: Bug

#1538 Fix false positives with simple Set/Map-initialized objects in `no-array-prototype-extensions` rule
  lib/rules/no-array-prototype-extensions.js
  tests/lib/rules/no-array-prototype-extensions.js
Labels: Bug

#1543 Fix false positive with Set/Map-initialized class properties in `no-array-prototype-extensions` rule
  lib/rules/no-array-prototype-extensions.js
  lib/rules/no-assignment-of-untracked-properties-used-in-tracking-contexts.js
  lib/rules/no-unused-services.js
  lib/utils/stack.js
  package.json
  tests/lib/rules/no-array-prototype-extensions.js
  yarn.lock
Labels: Bug

#1544 Fix false positive with Set/Map-initialized *private* class properties in `no-array-prototype-extensions` rule
  lib/rules/no-array-prototype-extensions.js
  tests/lib/rules/no-array-prototype-extensions.js
Labels: Bug

#1546 Fix false positives with `RSVP.Promise.reject()` in `no-array-prototype-extensions` rule
  lib/rules/no-array-prototype-extensions.js
  tests/lib/rules/no-array-prototype-extensions.js
Labels: Bug

#1545 Improve documentation for `no-*-prototype-extensions` rules
  docs/rules/no-array-prototype-extensions.md
  docs/rules/no-function-prototype-extensions.md
  docs/rules/no-string-prototype-extensions.md
Labels: Documentation
