Repository ember-cli/eslint-plugin-ember, pull requests merged in 2022-12, with the labels that each got.

#1693 Mention ESLint overrides for glob patterns in `no-restricted-service-injections` rule doc
  docs/rules/no-restricted-service-injections.md
Labels: Documentation

#1702 Add new rule `no-tracked-properties-from-args`
  README.md
  docs/rules/no-tracked-properties-from-args.md
  lib/rules/no-tracked-properties-from-args.js
  tests/lib/rules/no-tracked-properties-from-args.js
Labels: Enhancement

#1713 Switch to config file for `eslint-doc-generator`
  .eslint-doc-generatorrc.js
  package.json
Labels: Internal

#1712 Fix crash with `no-tracked-properties-from-args` rule
  lib/rules/no-tracked-properties-from-args.js
  tests/lib/rules/no-tracked-properties-from-args.js
Labels: Bug

#1720 Deprecate trivial node type check helpers
  lib/utils/types.js
Labels: Internal

#1714 Add new rule `no-implicit-injections`
  README.md
  docs/rules/no-implicit-injections.md
  lib/rules/no-implicit-injections.js
  lib/utils/ember.js
  package.json
  tests/lib/rules/no-implicit-injections.js
  tests/lib/utils/ember-test.js
  yarn.lock
Labels: Enhancement

#1715 Add new rule `no-deprecated-router-transition-methods`
  README.md
  docs/rules/no-deprecated-router-transition-methods.md
  lib/rules/no-deprecated-router-transition-methods.js
  lib/utils/decorators.js
  tests/lib/rules/no-deprecated-router-transition-methods.js
Labels: Enhancement
