Repository ember-cli/eslint-plugin-ember, pull requests merged in 2023-12, with the labels that each got.

#2018 Switch to ESLint flat config internally
  .eslint-doc-generatorrc.js
  .eslintignore
  .eslintrc.js
  eslint.config.js
  package.json
  yarn.lock
Labels: Internal

#1996 [gjs-gts-parser] fix type aware linting when using ts+gts files
  lib/parsers/gjs-gts-parser.js
  lib/parsers/transform.js
  lib/parsers/ts-utils.js
  package.json
  tests/lib/rules-preprocessor/ember_ts/bar.gts
  tests/lib/rules-preprocessor/ember_ts/baz.ts
  tests/lib/rules-preprocessor/ember_ts/foo.gts
  tests/lib/rules-preprocessor/gjs-gts-parser-test.js
  tests/lib/rules-preprocessor/tsconfig.eslint.json
  yarn.lock
Labels: Bug

#2027 Allow ember-data type registry imports in `use-ember-data-rfc-395-imports` rule
  docs/rules/use-ember-data-rfc-395-imports.md
  lib/rules/use-ember-data-rfc-395-imports.js
  tests/lib/rules/use-ember-data-rfc-395-imports.js
Labels: Bug

#2037 Add volta in package.json
  package.json
Labels: Internal

#2036 Add `lint:fix` script
  package.json
Labels: Internal

#2028 Move gjs/gts parser to `ember-eslint-parser` library
  README.md
  lib/config-legacy/base.js
  lib/config/base.js
  lib/index.js
  lib/parsers/gjs-gts-parser.js
  lib/parsers/transform.js
  lib/parsers/ts-utils.js
  lib/preprocessors/noop.js
  lib/utils/document.js
  package.json
  tests/lib/rules-preprocessor/gjs-gts-parser-test.js
  tests/lib/rules/template-indent.js
  tests/lib/rules/template-no-let-reference.js
  yarn.lock
Labels: Breaking

#2042 Update all dependencies
  package.json
  yarn.lock
Labels: Internal

#2045 Upgrade ember-eslint-parser
  package.json
  yarn.lock
Labels: Bug, dependencies

#2047 Remove unused dependency; @glimmer/syntax
  package.json
  yarn.lock
Labels: Internal

#2046 Fix issue with `no-deprecated-router-transition-methods` throwing errors outside of class usage
  lib/rules/no-deprecated-router-transition-methods.js
  tests/lib/rules/no-deprecated-router-transition-methods.js
Labels: Bug

#2048 Bump minimum version of ember-eslint-parser to `0.2.4`
  package.json
  yarn.lock
Labels: Bug, dependencies
