Repository ember-cli/eslint-plugin-ember, pull requests merged in 2023-05, with the labels that each got.

#1852 Only show `no-undef` errors for templates in gts files
  lib/preprocessors/glimmer.js
  lib/utils/document.js
  tests/lib/rules-preprocessor/gjs-gts-processor-test.js
Labels: Bug

#1853 Support autofix in gts files
  lib/preprocessors/glimmer.js
  lib/utils/document.js
  tests/lib/rules-preprocessor/gjs-gts-processor-test.js
Labels: Enhancement

#1865 Support autofix of numerical property access and ternary expressions in `no-get` rule
  lib/rules/no-get.js
  tests/lib/rules/no-get.js
Labels: Enhancement

#1866 Account for only having template tag in `no-empty-glimmer-component-classes` rule
  docs/rules/no-empty-glimmer-component-classes.md
  lib/rules/no-empty-glimmer-component-classes.js
  tests/lib/rules-preprocessor/gjs-gts-processor-test.js
Labels: Bug

#1868 [Docs] Use js syntax highlighting for no-empty-glimmer-component-classes
  .eslintignore
  docs/rules/no-empty-glimmer-component-classes.md
Labels: Documentation

#1869 Avoid crash with `inject` decorator in `no-restricted-service-injections` rule
  lib/rules/no-restricted-service-injections.js
  tests/lib/rules/no-restricted-service-injections.js
Labels: Bug

#1870 Fix crash with default computed property import in `no-unused-services` rule
  lib/rules/no-unused-services.js
  tests/lib/rules/no-unused-services.js
Labels: Bug

#1871 Avoid further decorator detection crashes in `no-restricted-service-injections` rule
  lib/rules/no-restricted-service-injections.js
  tests/lib/rules/no-restricted-service-injections.js
Labels: Bug

#1876 Allow generic type in TypeScript class in `no-empty-glimmer-component-classes` rule
  docs/rules/no-empty-glimmer-component-classes.md
  lib/rules/no-empty-glimmer-component-classes.js
  tests/lib/rules-preprocessor/gjs-gts-processor-test.js
  tests/lib/rules/no-empty-glimmer-component-classes.js
Labels: Bug

#1847 Add `useAt` option to autofix `.lastObject` to `.at(-1)` in `no-get` rule
  docs/rules/no-get.md
  lib/rules/no-get.js
  tests/lib/rules/no-get.js
Labels: Enhancement
