Repository ember-cli/eslint-plugin-ember, pull requests merged in 2023-11, with the labels that each got.

#1942 use custom parser for gts/gjs
  README.md
  lib/config/recommended.js
  lib/index.js
  lib/parsers/gjs-gts-parser.js
  lib/preprocessors/glimmer.js
  lib/preprocessors/noop.js
  lib/rules/no-empty-glimmer-component-classes.js
  lib/rules/no-unused-services.js
  lib/utils/document.js
  package.json
  tests/lib/rules-preprocessor/gjs-gts-parser-test.js
  tests/lib/rules-preprocessor/my-component.gts
  tests/lib/rules-preprocessor/tsconfig.eslint.json
  tests/lib/rules/no-empty-glimmer-component-classes.js
  yarn.lock
Labels: Enhancement

#1943 Add new rule `template-indent`
  README.md
  docs/rules/template-indent.md
  lib/rules/template-indent.js
  tests/lib/rules/template-indent.js
Labels: Enhancement

#1939 Add new rule `template-no-let-reference`
  .eslintignore
  README.md
  docs/rules/template-no-let-reference.md
  lib/parsers/gjs-gts-parser.js
  lib/rules/template-no-let-reference.js
  tests/lib/rules/template-no-let-reference.js
Labels: Enhancement

#1974 Update eslint-plugin-unicorn to v49
  lib/rules/no-array-prototype-extensions.js
  lib/rules/no-arrow-function-computed-properties.js
  lib/rules/no-deprecated-router-transition-methods.js
  lib/rules/no-get.js
  lib/rules/no-implicit-injections.js
  lib/rules/no-invalid-dependent-keys.js
  lib/rules/no-restricted-resolver-tests.js
  lib/rules/no-shadow-route-definition.js
  lib/rules/require-computed-macros.js
  lib/rules/require-computed-property-dependencies.js
  lib/rules/use-brace-expansion.js
  lib/utils/computed-properties.js
  lib/utils/computed-property-dependent-keys.js
  lib/utils/javascript.js
  lib/utils/property-getter.js
  lib/utils/stack.js
  package.json
  yarn.lock
Labels: Internal

#1975 Update almost all dependencies
  package.json
  yarn.lock
Labels: Enhancement

#1977 Add new `recommended` rule: `template-no-let-reference`
  README.md
  docs/rules/template-no-let-reference.md
  lib/recommended-rules.js
  lib/rules/template-no-let-reference.js
  tests/__snapshots__/recommended.js.snap
Labels: Breaking

#1984 Update `@typescript-eslint/` dependencies to v6
  lib/rules/no-empty-glimmer-component-classes.js
  package.json
  yarn.lock
Labels: Enhancement

#1981 Add `template-no-let-reference` rule to `recommended-gjs` and `recommended-gts` configs
  README.md
  docs/rules/template-no-let-reference.md
  lib/recommended-rules-gjs.js
  lib/recommended-rules-gts.js
  lib/recommended-rules.js
  lib/rules/template-indent.js
  lib/rules/template-no-let-reference.js
  scripts/update-rules.js
  tests/__snapshots__/recommended.js.snap
  tests/recommended.js
Labels: Breaking

#1990 docs: recommended-gts/gjs instead of gts/gjs-recommended
  README.md
Labels: Documentation

#1980 improve gts gjs configuration example
  README.md
Labels: Documentation

#1992 fix references for tags with a dot & non standard html tags
  lib/parsers/gjs-gts-parser.js
  lib/rules/template-no-let-reference.js
  package.json
  tests/lib/rules-preprocessor/gjs-gts-parser-test.js
  tests/lib/rules/template-no-let-reference.js
  yarn.lock
Labels: Bug

#1994 fix locations for ast after templates
  lib/parsers/gjs-gts-parser.js
  lib/utils/document.js
  tests/lib/rules-preprocessor/gjs-gts-parser-test.js
Labels: Bug

#2005 [gjs-gts-parser] fix parsing when there are multiple default <template> blocks (not allowed)
  lib/parsers/gjs-gts-parser.js
  tests/lib/rules-preprocessor/gjs-gts-parser-test.js
Labels: Bug
