Repository ember-cli/eslint-plugin-ember, pull requests merged in 2024-10, with the labels that each got.

#2191 Provide better gjs/gts config support for eslint 9
  eslint.config.js
  lib/recommended.mjs
  package.json
Labels: Enhancement

#2195 fix: Typo in error message
  package.json
  tests/lib/rules-preprocessor/gjs-gts-parser-test.js
  yarn.lock
Labels: Bug

#2196 Switch to pnpm + vitest (away from yarn @ 1 and jest)
  .github/workflows/ci.yml
  .npmrc
  README.md
  RELEASE.md
  docs/rules/no-unused-services.md
  docs/rules/route-path-style.md
  eslint.config.js
  lib/rules/no-get.js
  package.json
  pnpm-lock.yaml
  tests/__snapshots__/recommended.js.snap
  tests/config-setup.js
  tests/lib/rules-preprocessor/gjs-gts-parser-test.js
  tests/lib/utils/property-order-test.js
  tests/recommended.js
  tests/rule-setup.js
  vitest.config.mjs
  yarn.lock
Labels: Internal

#2198 Switch away from release-it to release-plan
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  CHANGELOG.md
  RELEASE.md
  package.json
  pnpm-lock.yaml
Labels: internal

#2200 Fix no-component-lifecycle-hook in double extended classic component
  lib/rules/no-component-lifecycle-hooks.js
  tests/lib/rules/no-component-lifecycle-hooks.js
Labels: bug
