Repository ember-cli/eslint-plugin-ember, pull requests merged in 2024-02, with the labels that each got.

#2088 add doc about gts imports in ts files
  README.md
Labels: Documentation

#2071 Fix nested classes case in `no-ember-super-in-es-classes`
  lib/rules/no-ember-super-in-es-classes.js
  tests/lib/rules/no-ember-super-in-es-classes.js
Labels: Bug

#2090 Refresh lockfile
  eslint.config.js
  yarn.lock
Labels: Internal

#2091 Upgrade ember-eslint-parser to 0.3.6
  package.json
  tests/lib/rules-preprocessor/gjs-gts-parser-test.js
  yarn.lock
Labels: Bug

#2092 Fix flat config for gts/gjs and `noop` parser name
  lib/config-legacy/base.js
  lib/config/base.js
  lib/index.js
Labels: Bug

#2093 Update linting
  eslint.config.js
  package.json
  yarn.lock
Labels: Internal
